### PR TITLE
Add fragmented ligands  without removal of non ring rotors.

### PR DESCRIPTION
**Pull request by jthorton**
- [X] Created a new folder in the submissions directory containing the dataset
- [X] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset is named `dataset.json`
- [X] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [ ] QCSubmit validation passed
- [ ] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
Looking good @jthorton! We'll push for getting the manager deployments ready to crunch on this!

**Comment by dotsdl** [comment]
We are ready to try this out. I'll make an announcement tomorrow morning PST. Thanks to @bennybp for deploying the conda env and Docker image for MM calcs!

**Comment by dotsdl** [comment]
@jthorton we're ready to go for compute! Looks like all this needs is a metadata fix for submission?

**Comment by jthorton** [comment]
Yup just put a blocker in there to make sure it wasn't merged before the managers were ready, thanks for getting that set up let's get this started!

**Comment by dotsdl** [comment]
Investigating why we're seeing 0 TorsionDrives running for the "openff-1.0.0" and "gaff-2.11" specs. This is unexpected to me.

**Comment by dotsdl** [comment]
Moved to "Requires Scientific Review" as this dataset is no longer advancing. It's likely that we can clear the final INCOMPLETE with work currently in progress on the public QCArchive server. We will park it here until we can test that functionality.

**Pull request merged**
