### PR TITLE
2nd Generation Torsion Datasets 

### PR DESCRIPTION
**Pull request by hyejang**
`2020-03-12-OpenFF-Gen-2-Torsion-Sets` were added. 
Main goal of the new dataset generation was a full coverage of torsion parameters with minimized data degeneracy. 
SIx input molecule sets were used for the dataset generation and datasets generated from each input molecule set were separated into folders with different data set names for further inspection. : 
    (1) Roche set (`2020-03-12-OpenFF-Gen-2-Torsion-Set-1-Roche`); 
    (2) Coverage set (`2020-03-12-OpenFF-Gen-2-Torsion-Set-2-Coverage`); 
    (3) Pfizer Discrepancy set (`2020-03-12-OpenFF-Gen-2-Torsion-Set-3-Pfizer-Discrepancy`); 
    (4) eMolecules Discrepancy set (`2020-03-12-OpenFF-Gen-2-Torsion-Set-4-eMolecules-Discrepancy`); 
    (5) Bayer set (`2020-03-12-OpenFF-Gen-2-Torsion-Set-5-Bayer`);
    (6) supplemental set (`2020-03-12-OpenFF-Gen-2-Torsion-Set-6-supplemental`) : input set of manually selected molecules for full coverage.

### CODE REVIEW

**Comment by hyejang** [comment]
@dgasmith Could you check if this PR looks good to go?

**Comment by hyejang** [comment]
@dgasmith  Heres the number of torsions in each collection. 409 1-D torsions in total. 
1. `OpenFF Gen 2 Torsion Set 1 Roche` : 65 1-D torsions (25 torsion scans are expected to be reused)
2. `OpenFF Gen 2 Torsion Set 2 Coverage`: 93 1-D torsions (56 torsion scans are expected to be reused)
3. `OpenFF Gen 2 Torsion Set 3 Pfizer Discrepancy`: 38 1-D torsions (10 torsion scans are expected to be reused)
4. `OpenFF Gen 2 Torsion Set 4 eMolecules Discrepancy`: 106 1-D torsions
5. `OpenFF Gen 2 Torsion Set 5 Bayer`: 100 1-D torsions
6. `OpenFF Gen 2 Torsion Set 6 supplemental`: 7 1-D torsions

**Comment by dgasmith** [comment]
@hyejang Ok, great. Are these ready to go?

**Comment by hyejang** [comment]
Yes, it looks good to go.

**Pull request merged**
