### PR TITLE
added 5 more torsiondrives

### PR DESCRIPTION
**Pull request by ChayaSt**
This PR adds five more torsiondrives to this set.

### CODE REVIEW

**Comment by dotsdl** [comment]
Awesome, thanks @ChayaSt! Ben and I will review and submit this in our session tomorrow morning.

**Comment by dotsdl** [comment]
@ChayaSt do we know what the current name of this dataset is? The closest matching dataset in QCArchive currently is `"SMIRNOFF Coverage Torsion Set 1"`, but the script `03_create_torsiondrive_dataset.py` refers to `"SMIRNOFF Coverage Torsion Set"`, which doesn't appear to exist any longer. 

From the age of the script (2019-07-25), it looks like this may have been a fairly early submission in the life of QCArchive. Could it be that the set this script points to got shuffled around somewhere? The set `"SMIRNOFF Coverage Torsion Set 1"` doesn't appear to match the entries in this submission, so we're puzzled as to where to actually direct this.

**Comment by ChayaSt** [comment]
@dotsdl, the name of the set was changed to:
`OpenFF Subsituted Phenyl Set 1`

**Comment by dotsdl** [comment]
Submitted both `["phenyl_set_input.tar.jz", "biphenyls_set_input.tar.gz"]`, which gave five (5) additional tasks. Output of script below:

```
Reading selected_torsions...
Found 144 torsions
Initializing dataset...
TorsionDriveDataset(name=`OpenFF Substituted Phenyl Set 1`, id='57', client='https://api.qcarchive.molssi.org:443/') 
Adding 144 torsions
0 CCC(=O)Nc1[cH:1][c:2](ccn1)[NH:3][CH2:4]C 2
0 CCCNc1cc[c:2]([cH:1]n1)[N:3](C)[CH3:4] 4
0 CCCNc1cc[c:2]([cH:1]n1)[O:3][CH2:4]C 10
0 CCCNc1ccc[c:2]([cH:1]1)[N:3]([CH3:4])C 5
0 CCCNc1ccc[c:2]([cH:1]1)[NH:3][CH3:4] 4
0 CCNc1[cH:1][c:2](ccn1)[NH:3][C:4](=O)NC 4
0 CCNc1[cH:1][c:2](ccn1)[O:3][C:4](=O)N 13
0 CCOC(=O)c1cc[cH:1][c:2](c1)[N+:3](=O)[O-:4] 4
0 CCOC(=O)c1ccc[c:2]([cH:1]1)[NH:3][C:4](=O)N(C)C 12
0 CCO[C:3](=[O:4])[c:2]1[cH:1]cc(cc1)NC(=O)C 2
0 CCO[C:3](=[O:4])[c:2]1[cH:1]cnc(c1)[N+](C)(C)C 4
0 CCOc1[cH:1][c:2](ccn1)[NH:3][C:4](=O)NC 2
0 CCOc1[cH:1][c:2](cnc1)[O:3][CH3:4] 2
0 CCOc1cc[c:2]([cH:1]n1)[C:3](=O)[O:4]CC 8
0 CC[C:4](=O)[NH:3][c:2]1[cH:1]c(cnc1)N 2
0 CC[C:4](=O)[NH:3][c:2]1[cH:1]cc(cc1)F 1
0 CC[C:4](=O)[NH:3][c:2]1cc(cn[cH:1]1)[N+](C)(C)C 2
0 CC[C:4](=O)[NH:3][c:2]1ccc(c[cH:1]1)N(C)C 1
0 CC[C:4](=O)[NH:3][c:2]1ccc(n[cH:1]1)C(=O)OCC 8
0 CC[C:4](=O)[NH:3][c:2]1ccc(n[cH:1]1)[N+](=O)[O-] 2
0 CC[C:4](=O)[NH:3][c:2]1ccc(n[cH:1]1)[N+](C)(C)C 2
0 CC[C:4](=O)[NH:3][c:2]1ccnc([cH:1]1)[N+](=O)[O-] 2
0 CC[C:4](=O)[NH:3][c:2]1ccnc([cH:1]1)[N+](C)(C)C 2
0 CC[CH2:4][NH:3][c:2]1[cH:1]cc(cc1)NC 3
0 CC[CH2:4][NH:3][c:2]1[cH:1]cc(nc1)NC(=O)NC 9
0 CC[CH2:4][NH:3][c:2]1cc(cn[cH:1]1)C(=O)OCC 18
0 CC[CH2:4][NH:3][c:2]1ccc(c[cH:1]1)[N+](C)(C)C 2
0 CC[CH2:4][NH:3][c:2]1ccc(n[cH:1]1)[N+](C)(C)C 4
0 CC[CH2:4][NH:3][c:2]1cccc([cH:1]1)NC(=O)N(C)C 18
0 CC[CH2:4][NH:3][c:2]1cccc([cH:1]1)[N+](C)(C)C 5
0 CC[CH2:4][NH:3][c:2]1ccnc([cH:1]1)C#N 3
0 CC[CH2:4][NH:3][c:2]1ccnc([cH:1]1)I 3
0 CC[CH2:4][NH:3][c:2]1ccnc([cH:1]1)[N+](C)(C)C 5
0 CC[O:4][C:3](=O)[c:2]1ccc(n[cH:1]1)N 2
0 CC[O:4][C:3](=O)[c:2]1cccc([cH:1]1)O 4
0 CC[O:4][C:3](=O)[c:2]1ccnc([cH:1]1)NC 6
0 CN(C)C(=O)Nc1c[cH:1][c:2](cc1)[NH:3][C:4](=O)N 7
0 CN(C)[C:4](=O)[NH:3][c:2]1[cH:1]cc(cc1)C(F)(F)F 2
0 CN(C)[C:4](=O)[NH:3][c:2]1[cH:1]cc(cc1)I 2
0 CN(C)[C:4](=O)[NH:3][c:2]1[cH:1]cc(cc1)[N+](C)(C)C 2
0 CN(C)[C:4](=O)[NH:3][c:2]1[cH:1]cc(nc1)[N+](C)(C)C 4
0 CN(C)[C:4](=O)[NH:3][c:2]1[cH:1]ccc(c1)[N+](C)(C)C 4
0 CN(C)[C:4](=O)[NH:3][c:2]1[cH:1]cnc(c1)[N+](=O)[O-] 4
0 CN(C)[C:4](=O)[NH:3][c:2]1[cH:1]cnc(c1)[N+](C)(C)C 4
0 CN(C)c1c[cH:1][c:2](cc1)[NH:3][C:4](=O)N 3
0 CN(C)c1c[cH:1][c:2](cc1)[O:3][CH3:4] 1
0 CN(C)c1c[cH:1][c:2](cn1)[NH:3][C:4](=O)N(C)C 4
0 CN(C)c1cc[cH:1][c:2](c1)[O:3][C:4](=O)N 6
0 CNC(=O)Nc1c[cH:1][c:2](cc1)[NH:3][C:4](=O)N(C)C 4
0 CN[C:4](=O)[NH:3][c:2]1[cH:1]cc(nc1)[N+](=O)[O-] 2
0 CN[C:4](=O)[NH:3][c:2]1[cH:1]cc(nc1)[N+](C)(C)C 2
0 CN[C:4](=O)[NH:3][c:2]1[cH:1]ccc(c1)N 2
0 CN[C:4](=O)[NH:3][c:2]1cc(cn[cH:1]1)[N+](C)(C)C 2
0 CN[C:4](=O)[NH:3][c:2]1ccc(c[cH:1]1)N(C)C 1
0 CN[C:4](=O)[NH:3][c:2]1ccc(c[cH:1]1)[N+](C)(C)C 1
0 CN[C:4](=O)[NH:3][c:2]1cccc([cH:1]1)[N+](C)(C)C 2
0 CNc1c[c:2]([cH:1]cn1)[N:3]([CH3:4])C 1
0 CNc1c[cH:1][c:2](cn1)[C:3](=[O:4])O 2
0 CNc1c[cH:1][c:2](cn1)[N+:3](=O)[O-:4] 1
0 C[C:4](=O)[NH:3][c:2]1[cH:1]c(cnc1)I 2
0 C[C:4](=O)[NH:3][c:2]1[cH:1]cc(nc1)[N+](C)(C)C 2
0 C[C:4](=O)[NH:3][c:2]1[cH:1]ccc(c1)N 2
0 C[C:4](=O)[NH:3][c:2]1[cH:1]cnc(c1)I 2
0 C[C:4](=O)[NH:3][c:2]1cc(cn[cH:1]1)[N+](C)(C)C 2
0 C[C:4](=O)[NH:3][c:2]1ccc(c[cH:1]1)N(C)C 1
0 C[C:4](=O)[NH:3][c:2]1ccc(c[cH:1]1)[N+](C)(C)C 1
0 C[C:4](=O)[NH:3][c:2]1ccc(n[cH:1]1)[N+](=O)[O-] 2
0 C[C:4](=O)[NH:3][c:2]1cccc([cH:1]1)[N+](C)(C)C 2
0 C[CH2:4][NH:3][c:2]1[cH:1]c(cnc1)OCC 4
0 C[CH2:4][NH:3][c:2]1[cH:1]cc(cc1)N(C)C 1
0 C[CH2:4][NH:3][c:2]1[cH:1]cc(nc1)N 1
0 C[CH2:4][NH:3][c:2]1[cH:1]cc(nc1)[N+](C)(C)C 1
0 C[CH2:4][NH:3][c:2]1[cH:1]cnc(c1)Br 1
0 C[CH2:4][NH:3][c:2]1[cH:1]cnc(c1)Cl 1
0 C[CH2:4][NH:3][c:2]1ccc(c[cH:1]1)[N+](=O)[O-] 1
0 C[CH2:4][NH:3][c:2]1ccnc([cH:1]1)[N+](C)(C)C 2
0 C[CH2:4][O:3][c:2]1[cH:1]cc(cc1)I 1
0 C[CH2:4][O:3][c:2]1[cH:1]cc(cc1)[N+](C)(C)C 1
0 C[CH2:4][O:3][c:2]1[cH:1]cc(nc1)C(=O)O 4
0 C[CH2:4][O:3][c:2]1[cH:1]cc(nc1)[N+](=O)[O-] 2
0 C[CH2:4][O:3][c:2]1[cH:1]cc(nc1)[N+](C)(C)C 2
0 C[CH2:4][O:3][c:2]1[cH:1]cnc(c1)OC(=O)N 8
0 C[CH2:4][O:3][c:2]1cccc([cH:1]1)NC(=O)N(C)C 7
0 C[CH2:4][O:3][c:2]1ccnc([cH:1]1)[N+](C)(C)C 2
0 C[N+](C)(C)c1[cH:1][c:2](ccn1)[NH:3][C:4](=O)N 6
0 C[N+](C)(C)c1[cH:1][c:2](cnc1)[O:3][C:4](=O)N 7
0 C[N+](C)(C)c1c[c:2]([cH:1]cn1)[C:3](=[O:4])O 2
0 C[N+](C)(C)c1c[c:2]([cH:1]cn1)[N+:3](=O)[O-:4] 1
0 C[N+](C)(C)c1c[c:2]([cH:1]cn1)[O:3][CH3:4] 1
0 C[N+](C)(C)c1c[cH:1][c:2](cn1)[NH:3][C:4](=O)N 4
0 C[N+](C)(C)c1c[cH:1][c:2](cn1)[O:3][C:4](=O)N 4
0 C[N+](C)(C)c1c[cH:1][c:2](cn1)[O:3][CH3:4] 1
0 C[N+](C)(C)c1cc[c:2]([cH:1]c1)[O:3][C:4](=O)N 3
0 C[N+](C)(C)c1cc[cH:1][c:2](c1)[O:3][CH3:4] 1
0 C[N+](C)(C)c1ccc[c:2]([cH:1]1)[NH:3][C:4](=O)N 6
0 C[N:3]([CH3:4])[c:2]1[cH:1]ccc(c1)NC(=O)N(C)C 4
0 C[N:3]([CH3:4])[c:2]1cc(cn[cH:1]1)[N+](C)(C)C 1
0 C[N:3]([CH3:4])[c:2]1ccc(c[cH:1]1)[N+](C)(C)C 1
0 [CH3:4][N:3](C)[c:2]1[cH:1]cc(cc1)N(C)C 1
0 [CH3:4][N:3](C)[c:2]1[cH:1]cc(nc1)[N+](=O)[O-] 1
0 [CH3:4][N:3](C)[c:2]1[cH:1]cc(nc1)[N+](C)(C)C 1
0 [CH3:4][N:3](C)[c:2]1[cH:1]ccc(c1)OC(=O)N 6
0 [CH3:4][N:3](C)[c:2]1ccc(n[cH:1]1)C(F)(F)F 1
0 [CH3:4][NH:3][c:2]1[cH:1]c(cnc1)C(=O)O 4
0 [CH3:4][NH:3][c:2]1[cH:1]cc(cc1)NC 1
0 [CH3:4][NH:3][c:2]1[cH:1]cc(cc1)[N+](=O)[O-] 1
0 [CH3:4][NH:3][c:2]1[cH:1]cc(nc1)C(=O)O 2
0 [CH3:4][NH:3][c:2]1[cH:1]cc(nc1)O 1
0 [CH3:4][NH:3][c:2]1[cH:1]cc(nc1)[N+](C)(C)C 1
0 [CH3:4][NH:3][c:2]1[cH:1]cnc(c1)N 1
0 [CH3:4][NH:3][c:2]1cc(cn[cH:1]1)[N+](C)(C)C 1
0 [CH3:4][NH:3][c:2]1ccnc([cH:1]1)[N+](C)(C)C 1
0 [CH3:4][O:3][c:2]1[cH:1]cc(nc1)[N+](=O)[O-] 1
0 [CH3:4][O:3][c:2]1[cH:1]ccc(c1)C(=O)O 4
0 [CH3:4][O:3][c:2]1[cH:1]cnc(c1)I 1
0 [H:4][NH:3][c:2]1[cH:1]c(cnc1)NC(=O)NC 2
0 [H:4][NH:3][c:2]1[cH:1]c(cnc1)[N+](C)(C)C 1
0 [H:4][NH:3][c:2]1[cH:1]cc(cc1)C(=O)OCC 1
0 [H:4][NH:3][c:2]1[cH:1]cc(cc1)N(C)C 1
0 [H:4][NH:3][c:2]1[cH:1]cc(cc1)[N+](C)(C)C 1
0 [H:4][NH:3][c:2]1[cH:1]cc(nc1)OC 1
0 [H:4][NH:3][c:2]1[cH:1]cc(nc1)[N+](=O)[O-] 1
0 [H:4][NH:3][c:2]1[cH:1]cnc(c1)[N+](=O)[O-] 1
0 [H:4][NH:3][c:2]1ccc(n[cH:1]1)[N+](C)(C)C 1
0 [H:4][O:3][c:2]1[cH:1]cc(cc1)[N+](=O)[O-] 1
0 [H:4][O:3][c:2]1[cH:1]ccc(c1)C 1
0 [H:4][O:3][c:2]1[cH:1]cnc(c1)N 1
0 [H:4][O:3][c:2]1cc(cn[cH:1]1)NC(=O)N(C)C 4
0 [H:4][O:3][c:2]1cc(cn[cH:1]1)[N+](C)(C)C 1
0 [H:4][O:3][c:2]1ccc(c[cH:1]1)N(C)C 1
0 [H:4][O:3][c:2]1ccc(n[cH:1]1)[N+](C)(C)C 1
0 [H:4][O:3][c:2]1cccc([cH:1]1)[N+](C)(C)C 1
0 [H:4][O:3][c:2]1ccnc([cH:1]1)[N+](C)(C)C 1
0 [cH:1]1[c:2](cncc1OC(=O)N)[NH:3][C:4](=O)N 20
0 [cH:1]1cc(nc[c:2]1[C:3](=[O:4])O)C#N 2
0 [cH:1]1cc(nc[c:2]1[N+:3](=O)[O-:4])F 1
0 [cH:1]1cc(nc[c:2]1[N+:3](=O)[O-:4])NC(=O)N 3
0 [cH:1]1cc(nc[c:2]1[NH:3][C:4](=O)N)[N+](=O)[O-] 4
0 [cH:1]1cc(nc[c:2]1[O:3][C:4](=O)N)[N+](=O)[O-] 4
0 [cH:1]1cnc(c[c:2]1[N+:3](=O)[O-:4])N 1
0 [cH:1]1cnc(c[c:2]1[NH:3][C:4](=O)N)[N+](=O)[O-] 6
0 c1cc(c[c:2]([cH:1]1)[NH:3][C:4](=O)N)C(=O)O 11
0 c1cc(c[cH:1][c:2]1[C:3](=[O:4])O)NC(=O)N 5
0 c1cnc([cH:1][c:2]1[C:3](=[O:4])O)NC(=O)N 7
Submitting tasks...
0
Complete!
Found 15 torsions
Initializing dataset...
TorsionDriveDataset(name=`OpenFF Substituted Phenyl Set 1`, id='57', client='https://api.qcarchive.molssi.org:443/') 
Adding 15 torsions
0 [cH:1]1cc(cc[c:2]1[c:3]2[cH:4]c[nH+]cc2)O 5
0 [cH:1]1cc(cc[c:2]1[c:3]2[cH:4]c[nH+]cc2)[O-] 5
0 [cH:1]1cc(cc[c:2]1[c:3]2[cH:4]cncc2)O 5
0 [cH:1]1cc(cc[c:2]1[c:3]2[cH:4]cncc2)[O-] 5
0 c1[cH:1][c:2](c(cc1O)Cl)[c:4]2[cH:3]c[nH+]cc2 5
1 c1[cH:1][c:2](c(cc1O)Cl)[c:4]2[cH:3]cncc2 5
2 c1[cH:1][c:2](c(cc1O)F)[c:4]2[cH:3]c[nH+]cc2 5
2 c1[cH:1][c:2](c(cc1O)F)[c:4]2[cH:3]cncc2 5
2 c1[cH:1][c:2](c(cc1[O-])Cl)[c:4]2[cH:3]c[nH+]cc2 5
3 c1[cH:1][c:2](c(cc1[O-])Cl)[c:4]2[cH:3]cncc2 5
4 c1[cH:1][c:2](c(cc1[O-])F)[c:4]2[cH:3]c[nH+]cc2 5
4 c1[cH:1][c:2](c(cc1[O-])F)[c:4]2[cH:3]cncc2 5
4 c1c[cH:1][c:2](cc1)[c:3]2[cH:4]cncc2 5
4 c1ccc([c:2]([cH:1]1)[c:3]2[cH:4]cncc2)Cl 5
5 c1ccc([c:2]([cH:1]1)[c:3]2[cH:4]cncc2)F 5
Submitting tasks...
5
Complete!
```

**Pull request merged**
