### PR TITLE
genentech set2 with molecules that have more than three rotors fragme…

### PR DESCRIPTION
**Pull request by pavankum**
…nted

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset is named `dataset.json`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [ ] Make a new dataset entry in the mapping table, INDEX.md
- [x] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
@pavankum do you mind if I rename the compute spec used here to `default-dlc`? Otherwise looking great!

**Comment by pavankum** [comment]
Sure @dotsdl, thanks for the review!

**Review by dotsdl — APPROVED** [review]
Great work @pavankum! Submitting!

**Comment by pavankum** [comment]
Hi @dotsdl, can you please move this to scientific review, the error rate seems high, I will take a look later

**Comment by dotsdl** [comment]
Good call @pavankum; moved to "Requires Scientific Review".

**Pull request merged**
