### PR TITLE
OpenFF Industry Benchmark Season 1 - MM v1.1

### PR DESCRIPTION
**Pull request by dotsdl**
MM optimizations based on completed QM optimization final geometries from the `OpenFF Industry Benchmark Season 1 v1.1` dataset.

## New Submission Checklist

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [ ] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Made a new dataset entry in the mapping table in repository `README.md`
- [x] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
@jthorton please review when you have a chance. @bennybp and I managed to get the [MM specs](https://github.com/openforcefield/qca-dataset-submission/pull/208) on the original submission unstuck, so getting this merged is somewhat less urgent. I will be officially back online Wednesday, Tuesday earliest, to address any comments.

Thank you!

**Comment by pavankum** [comment]
@dotsdl I don't have the benchmark env set up so I am not sure how the dataset was generated using 
`!openff-benchmark optimize create-submittable -o "dataset-mm.json.bz2" --dataset-name "OpenFF Industry Benchmark Season 1 - MM v1.1" --season "1:2" data/results-qm/default/`. 

Some warnings during the above step seem to be dangerous like, 
- `Warning: molecule is tagged as 3D, but all Z coords are zero`, 
- `WARNING: Charges were rearranged`, 
- `WARNING: Proton(s) added/removed`, 
but if I read the molecules in the final dataset.json file they look fine, it's a bit confusing.

Another thing I observed is that all the molecules in the json have a BRI tag which represents only one company, is it the intent or others might be missing? I think @jthorton would be in a better place to review this PR. If his plate his full I can take another look.

**Comment by dotsdl** [comment]
> @dotsdl I don't have the benchmark env set up so I am not sure how the dataset was generated using
> `!openff-benchmark optimize create-submittable -o "dataset-mm.json.bz2" --dataset-name "OpenFF Industry Benchmark Season 1 - MM v1.1" --season "1:2" data/results-qm/default/`.
> 

Ah, thank you! I've now added an env file that builds the environment I used. The inputs to `create-submittable` are the outputs from the `export`, which is SDF files giving the final geometry of all QM optimizations from "OpenFF Industry Benchmark Season 1 v1.1".

> Some warnings during the above step seem to be dangerous like,
> 
>     * `Warning: molecule is tagged as 3D, but all Z coords are zero`,

In working with the partners, I think we identified these warnings as all being molecules that are flat/2D, even though the SDFs themselves are all 3D. Would have to do a more thorough analysis to determine if this is true for all cases, however. @j-wags is this consistent with your memory?
> 
>     * `WARNING: Charges were rearranged`,
> 
>     * `WARNING: Proton(s) added/removed`,
>       but if I read the molecules in the final dataset.json file they look fine, it's a bit confusing.

We encounter these a lot with taking the QM mols and running them through RDKIT. @j-wags I think we had concluded in the benchmark work with partners that these weren't too concerning? I don't recall our conclusions off-hand, however.

> Another thing I observed is that all the molecules in the json have a BRI tag which represents only one company, is it the intent or others might be missing? I think @jthorton would be in a better place to review this PR. If his plate his full I can take another look.

I'm seeing the following prefixes among the keys under the top-level `'dataset'` key:
```
{'BRI', 'GNT', 'JNS', 'MRK', 'RCH', 'WCS', 'XTP'}
```

@pavankum where are you only seeing `BRI` represented?

**Comment by j-wags** [comment]
> In working with the partners, I think we identified these warnings as all being molecules that are flat/2D, even though the SDFs themselves are all 3D. Would have to do a more thorough analysis to determine if this is true for all cases, however. @j-wags is this consistent with your memory?

Yes, the "2D" warnings are just fine. Some molecules are planar, and some conformer generation methods have a convention of laying them flat with all z=0, which can make RDKit emit this warning on subsequent reads of that file. 

>> * `WARNING: Proton(s) added/removed`,
>>   but if I read the molecules in the final dataset.json file they look fine, it's a bit confusing.

> We encounter these a lot with taking the QM mols and running them through RDKIT. @j-wags I think we had concluded in the benchmark work with partners that these weren't too concerning? I don't recall our conclusions off-hand, however.

Yup, these are fine too. IIRC, we tracked this down to the InChI toolkit populating metadata for the submission and doing weird InChI stuff to the protonation in the process. It doesn't affect the underlying molecule.

**Comment by pavankum** [comment]
@dotsdl Awesome! Thank you very much for the clarifications. 


 >  where are you only seeing BRI represented?

That was my mistake, sorry about that. I printed out the dataset and didn't notice that it was truncated after a few records with three tiny extension dots. I printed the dataset keys and all the tags you mentioned are present, and the total no. of entries is 71655.

One last minor block for me, I created the env and tried `openff-benchmark optimize export `,  but it is throwing the following error for me,

```
Traceback (most recent call last):
  File "/home/maverick/anaconda3/envs/openff-benchmark-optimization-export-multi/bin/openff-benchmark", line 5, in <module>
    from openff.benchmark.cli import cli
  File "/home/maverick/anaconda3/envs/openff-benchmark-optimization-export-multi/lib/python3.7/site-packages/openff/benchmark/cli.py", line 492, in <module>
    @click.option('--output-directory', default='5-compare_forcefields', required=True)
  File "/home/maverick/anaconda3/envs/openff-benchmark-optimization-export-multi/lib/python3.7/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/home/maverick/anaconda3/envs/openff-benchmark-optimization-export-multi/lib/python3.7/site-packages/click/core.py", line 2482, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/home/maverick/anaconda3/envs/openff-benchmark-optimization-export-multi/lib/python3.7/site-packages/click/core.py", line 2110, in __init__
    ) from None
ValueError: 'default' must be a list when 'multiple' is true.
```
When I replace `multiple=True` in cli.py with `multiple=False` I was able to run the command and generate SDF files so this is a non-issue for me, I don't want to delay further and pushing this submission through. You can merge this as it is.

**Review by pavankum — APPROVED** [review]
Thank you for building this dataset!!

**Comment by dotsdl** [comment]
> One last minor block for me, I created the env and tried `openff-benchmark optimize export `, but it is throwing the following error for me,
> 
> ```
> Traceback (most recent call last):
>   File "/home/maverick/anaconda3/envs/openff-benchmark-optimization-export-multi/bin/openff-benchmark", line 5, in <module>
>     from openff.benchmark.cli import cli
>   File "/home/maverick/anaconda3/envs/openff-benchmark-optimization-export-multi/lib/python3.7/site-packages/openff/benchmark/cli.py", line 492, in <module>
>     @click.option('--output-directory', default='5-compare_forcefields', required=True)
>   File "/home/maverick/anaconda3/envs/openff-benchmark-optimization-export-multi/lib/python3.7/site-packages/click/decorators.py", line 247, in decorator
>     _param_memo(f, OptionClass(param_decls, **option_attrs))
>   File "/home/maverick/anaconda3/envs/openff-benchmark-optimization-export-multi/lib/python3.7/site-packages/click/core.py", line 2482, in __init__
>     super().__init__(param_decls, type=type, multiple=multiple, **attrs)
>   File "/home/maverick/anaconda3/envs/openff-benchmark-optimization-export-multi/lib/python3.7/site-packages/click/core.py", line 2110, in __init__
>     ) from None
> ValueError: 'default' must be a list when 'multiple' is true.
> ```
> 
> When I replace `multiple=True` in cli.py with `multiple=False` I was able to run the command and generate SDF files so this is a non-issue for me, I don't want to delay further and pushing this submission through. You can merge this as it is.

Ah, I forgot we pinned `click=7.1.2` in the prod envs to keep it from drifting forward on us. The issue you identified and fixed is also fixed in `master`, I think, but we pinned `click` anyway to avoid additional surprises coming down for our prod envs. I've pinned this in the env file in this submission as well to avoid the issue fore reproducibility.

**Comment by dotsdl** [comment]
Thanks @pavankum! Will merge this with fresh eyes in the morning. Much appreciate for the thorough review!

**Review by jthorton — APPROVED** [review]
Great job @dotsdl, LGTM.

**Pull request merged**
