### PR TITLE
RNA Trinucleotide Single Point Dataset v1.0

### PR DESCRIPTION
**Pull request by kntkb**
## New Submission Checklist

- [ ] Created a new folder in the submissions directory containing the dataset
- [ ] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [ ] All files used to produce the dataset are included with a description
- [ ] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [ ] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [ ] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [ ] QCSubmit validation passed
- [ ] Made a new dataset entry in the mapping table in repository `README.md`
- [ ] Ready to submit!

## Compute Expansion Checklist

- [ ] Compute expansion filename matches pattern `compute*.json`; may feature a compression extension, such as `.bz2`
- [ ] QCSubmit validation passed
- [ ] Ready to submit!

### CODE REVIEW

**Comment by kntkb** [comment]
Hi @pavankum! I made a new dataset for RNA trinucleotides. I would be grateful if someone can review the PR and approve the QC submission.

**Comment by pavankum** [comment]
Hi @kntkb, thanks for the submission, I can take a look by tomorrow.

**Comment by pavankum** [comment]
Hi @kntkb, we still have an issue to validate PRs from a fork so we granted access to you for the repo, can you please clone the repo, create a new branch, copy the files for this new submission, and redo the PR. 

FYI, we use a new branch for every dataset and squash merge so it is better to not overlap any old dataset submissions or work on the same branch for different dataset submissions, which may result in github history conflicts.

**Comment by kntkb** [comment]
Thank you @pavankum. I will close this PR and redo the submission.

**Pull request closed without merging**
