### PR TITLE
Pr/300

### PR DESCRIPTION
**Pull request by pavankum**

### CODE REVIEW

**Comment by pavankum** [comment]
LGTM! Ported the updates from #300 to here.

**Comment by pavankum** [comment]
@dotsdl @chapincavender I reviewed this one and it is good to go, please approve this when you have time. This is a port of #300.

**Review by chapincavender — APPROVED** [review]
LGTM! Everything looks good to go for computation. A few minor changes for the README, but these shouldn't block submission and can be addressed later. Just wanted to document them while I'm thinking about it.

* I don't see that the main README for the repo was changed to point to this dataset. Was that in a previous PR?
* In the manifest, for the pickle files, change the description from "the main input for the dataset" to something more descriptive that differentiates them.
* In the manifest for `dataset.json.bz`, change "gradient dataset" to "basic dataset"
* In the manifest for `dataset.smi`, change "peptide" to "nucleic acids" or similar.

**Comment by pavankum** [comment]
Thank you very much @chapincavender! Updated the readme files now.

**Comment by pavankum** [comment]
@kntkb Calculations with the `openff-default` QC specification finished, and remaining 114 are persistent SCF convergence errors. For the other QC spec (`wb97m-d3bj/def2-tzvppd`) the basis set is pretty large and the completion rate is much slower, so it may take a while to finish with current compute resources. 

Accessing the data is a bit tricky for single points datasets, so if you want to look at the data we already have I am attaching a jupyter notebook for your reference (please rename the file to `*.ipynb` after download). Please do note the split of `B3LYP-D3BJ` calculation into `B3LYP` and `D3BJ`, and how to access each of those outputs. The same reason why you would see 8978 calculations for `default` in the above bot report, which is two times 4489.
 
[rna_dataset_access.ipynb.txt](https://github.com/openforcefield/qca-dataset-submission/files/9192066/rna_dataset_access.ipynb.txt)

**Comment by kntkb** [comment]
Hi @pavankum! Perhaps we can stop the recalculation for the incomplete datasets since the most important ones are already complete. I can look into the incomplete datasets and prepare a better initial structure if necessary.

**Comment by pavankum** [comment]
Thank you for the feedback @kntkb. Sure, will move this to end-of-life then.

**Pull request merged**
