### PR TITLE
[WIP] Add Genentech dataset to prep for optimization dataset

### PR DESCRIPTION
**Pull request by davidlmobley**
Adds source files for [Genentech PDB Ligand Expo dataset](https://github.com/openforcefield/open-forcefield-data/pull/30), to prep. This is the full, unprocessed set, which separates out charged and neutral compounds. I suggest we slice and dice this a couple of ways:

1. Optimization dataset as provided (filtering out largest molecules if needed??). Perhaps filter molecules with > 3 rotors and see what's left.
2. Optimization dataset after fragmentation
3. Torsion drive dataset after fragmentation

Negatively charged compounds may not perform well with current reference QC method, but we can run them for now and filter out before utilizing for testing/benchmarking, then revisit with better method later. 

To do:
- [ ] Filter by size for initial optimization dataset
- [ ] Prep initial optimization set for submission
- [ ] Fragment for secondary optimization dataset
- [ ] Prep secondary optimization set for submission
- [ ] Fragment for torsion drive set
- [ ] Prep torsion drive set for submission

### CODE REVIEW

**Comment by jchodera** [comment]
If we need to filter for size for an initial optimization dataset, what is the maximum number of heavy atoms we should submit for an `OptimizationDataset`? This dataset has already been filtered for MW <= 500.

**Comment by dotsdl** [comment]
@davidlmobley is this submission still of interest to us? If not, we will close it for now and re-open if needed.

**Comment by davidlmobley** [comment]
Still of interest, but not urgent; tagging @jthorton to get this on his radar.

**Comment by j-wags** [comment]
Since our queue is emptying out, @jthorton will go ahead and try to prepare this dataset for submission tomorrow. A few questions came up:
*  whether to keep this in a single dataset or split into many. We propose the following:
    * Optimization dataset as provided (filtering out largest molecules if needed??). Perhaps filter molecules with > 3 rotors and see what's left.
       * `Genentech PDB Ligand Expo whole optimization neutral v1.0` --> low priority, submitted first 
       * `Genentech PDB Ligand Expo whole optimization charged v1.0` --> low priority, submitted fourth 
    * Optimization dataset after fragmentation
        * `Genentech PDB Ligand Expo fragment optimization neutral v1.0` --> low priority, submitted second 
        * `Genentech PDB Ligand Expo fragment optimization charged v1.0` --> low priority, submitted fifth 
    * Torsion drive dataset after fragmentation
        * `Genentech PDB Ligand Expo fragment torsiondrive neutral v1.0` --> low priority, submitted third 
        * `Genentech PDB Ligand Expo fragment torsiondrive charged v1.0` --> low priority, submitted sixth 
* Whether to enumerate stereoisomers and tautomers?
    * We propose to enumerate these states

**Comment by pavankum** [comment]
Filtering > 3 rotors leaves around 127 molecules out of 646, which is only 20% of the original set. Uploaded preliminary data, generated with and without filtering, for a discussion.

**Pull request merged**
