### PR TITLE
Genentech set1

### PR DESCRIPTION
**Pull request by pavankum**
- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset is named `dataset.json`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
@pavankum are you ready for a review for this submission?

**Comment by pavankum** [comment]
> @pavankum are you ready for a review for this submission?

yeah, this is ready for review

**Comment by dotsdl** [comment]
Excellent, thanks! @trevorgokey, do you have time to review this submission this week? If not, I can review on Friday earliest.

**Comment by pavankum** [comment]
@trevorgokey and @dotsdl no hurry on these set of submissions

**Comment by pavankum** [comment]
Awesome! Thank you very much @dotsdl

**Comment by dotsdl** [comment]
Remaining errors are looking persistent. We should try and reproduce locally with QCEngine. Can you do this @pavankum?

**Comment by pavankum** [comment]
@dotsdl Sure David, I will dig into those

**Comment by dotsdl** [comment]
Great, thanks! Moving this into "Requires Scientific Review". Please report any conclusions or recommendations for next steps here.

**Comment by pavankum** [comment]
@dotsdl Sorry for the delay in getting to this. 
I checked the errors, two of them failed to converge at the end of geometry optimization (33668440, 33668615), I ran them on uci cluster with the new 'dlc' setting and they both converged. 
The other errors are similar to the unknown errors in pepconf, I ran three of them, one of them converged (33668243), and the other two (33668376, 33668436) got started without any trouble (was using free queue and these two got preempted during the run). Please let me know if I have to resubmit the errored out ones separately with the new fixes.

**Pull request merged**
