### PR TITLE
Add a theory benchmarking set w/ B3LYP-D3BJ/DZVP

### PR DESCRIPTION
**Pull request by hyejang**
- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset is named `dataset.json`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Ready to submit!

### CODE REVIEW

**Comment by hyejang** [comment]
@jthorton, could you check if this looks good to go?

**Comment by hyejang** [comment]
@jthorton, could you check if this looks good to go?

**Comment by jthorton** [comment]
This looks good to me we just need the CI to pick it up first before we submit Ill look into whats happening.

**Comment by dotsdl** [comment]
@jthorton re-running now. That's a puzzling error to me too. It might be intermittent.

**Comment by dotsdl** [comment]
The secret credentials for Dangerbot can't be used on a fork, so that is the likely cause here. We will consider alternatives to make this work in the future.

@hyejang I've added you as a collaborator (I'm sorry you weren't one already). You can now push branches directly to this repo, but please don't push to `master` (we may add a guard against this soon to avoid accidents). Can you make a new PR using a branch besides `master` pushed to this repo?

**Comment by hyejang** [comment]
sure, sounds good. I'll close this PR and open new one then.

**Pull request closed without merging**
