### PR TITLE
[pepconf-dlc] Added default-dlc compute spec to PEPCONF dataset

### PR DESCRIPTION
**Pull request by dotsdl**
- [ ] Created a new folder in the submissions directory containing the dataset
- [ ] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [ ] All files used to produce the dataset are included with a description
- [ ] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [ ] Dataset is named `dataset.json`
- [ ] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [ ] Make a new dataset entry in the mapping table, INDEX.md
- [ ] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
@pavankum please review my parameter choices, and let me know if I need to change or add anything for this submission! This is the re-roll of PEPCONF with DLC internal coordinates and `reset=True` for geomeTRIC. 

I've also upped the `maxiter` for SCF to 300 and for geomeTRIC to 500 as a bit of hedging in case some of these crazy molecules still require quite a bit to converge.

**Review by pavankum — APPROVED** [review]

**Comment by pavankum** [comment]
@dotsdl this looks great, I don't have anything else to add to the parameter choices now, you can merge.

**Comment by dotsdl** [comment]
@pavankum thank you! Merging!

**Comment by dotsdl** [comment]
Hmmm...something appears wrong with this submission. We get a response of 0 from QCArchive, and when I do a
```
from qcportal import FractalClient

cl = FractalClient()
ds = cl.get_collection("OptimizationDataset", "OpenFF PEPCONF OptimizationDataset v1.0")
ds.status()
```
I get:
```
            default  ani2x-qm  default-dlc
COMPLETE       1805       NaN          NaN
ERROR          5749    7560.0          NaN
INCOMPLETE        6       NaN          NaN
```

@jthorton do we know this could be an issue in latest QCSubmit?

**Comment by dotsdl** [comment]
Also, question before we proceed much further: do we want wavefunction data saved for these optimizations?

**Comment by jthorton** [comment]
Just had a little look into this and doing `ds.data.history` shows all the specs that have been used to create tasks and I get 
>  {'ani2x-qm', 'default'}
I think this is due to the threading update in QCSubmit, the tasks are chunked up between threads using the list of submitted indices, as this is a compute expansion there are no new indices so no tasks are made. Ill make a fix in QCSubmit to create tasks based on the entries present in the dataset if we are not adding any new entries which should fix this. 

On the wavefunction side, I am not sure if we tested if saving during optimizations would save it for every result in the trajectory which might be a lot of data which might never be used (not 100% sure) we can always calculate it for the optimised geometries if we need after.

**Comment by dotsdl** [comment]
Excellent, thank you @jthorton! We'll try submitting again once we have a fix in QCSubmit, no problem.

Re: wavefunctions, agreed. We'll leave these off since that could be a lot of data that no one is interested in being stored. If it can be done in post, that's perfect.

**Comment by dotsdl** [comment]
@jthorton is putting together a fix in `openff.qcsubmit` to allow resubmission of this PR; aiming to resubmit today.

**Comment by dotsdl** [comment]
I've set this up to Error Cycle again; however, compute tag on all tasks has been set to `openff-himem`, which will restrict execution to only managers with this tag included in their supported tag list. This is currently the case for our PRP deployment.

**Pull request merged**
