### PR TITLE
Add OpenFF BCC Refit Study COH v1.0

### PR DESCRIPTION
**Pull request by SimonBoothroyd**
## New Submission Checklist

- [X] Created a new folder in the submissions directory containing the dataset
- [X] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [X] All files used to produce the dataset are included with a description
- [X] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [X] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [X] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [ ] QCSubmit validation passed
- [ ] Made a new dataset entry in the mapping table in repository `README.md`
- [ ] Ready to submit!

## Compute Expansion Checklist

- [ ] Compute expansion filename matches pattern `compute*.json`; may feature a compression extension, such as `.bz2`
- [ ] QCSubmit validation passed
- [ ] Ready to submit!

### CODE REVIEW

**Review by pavankum — APPROVED** [review]
Thanks for putting this together @SimonBoothroyd! LGTM merging as it is.

**Comment by pavankum** [comment]
@dotsdl enabling submission workflow github action to get this submission through, will disable after this goes in

**Comment by SimonBoothroyd** [comment]
Thanks @pavankum - it seems I added the default spec by mistake! Would it be difficult to drop it?

**Comment by pavankum** [comment]
@SimonBoothroyd I think we can drop it, I stopped the submission lifecycle, will check if anything went through or not and push it back to compute.

**Comment by SimonBoothroyd** [comment]
Perfect - thanks so much @pavankum! And sorry you got the notifications on the weekend, I'd assumed you wouldn't see until Monday!

**Comment by pavankum** [comment]
@SimonBoothroyd No worries! I checked the submission and it didn't create any result records, also I made a huge mistake in the review in a hurry to push to compute, apologies for that! The dataset name refers to an old one, should be changed to `"OpenFF ESP Fragment Conformers v1.0"`, and the default spec can be removed by adding `dataset.qc_specifications.pop('default')`. I couldn't regenerate the dataset file with these changes since `esp-fragment-set-complete.pkl` is missing. Can you add that file for provenance purposes.

**Pull request merged**
