### PR TITLE
add single point energy calculations

### PR DESCRIPTION
**Pull request by pavankum**
## New Submission Checklist

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Made a new dataset entry in the mapping table in repository `README.md`
- [x] Ready to submit!

### CODE REVIEW

**Comment by pavankum** [comment]
@dotsdl @jthorton when you have a moment can you check what's failing in this submission. I am building a single point energy calculation dataset for the final geometries from a torsiondrive dataset. I used BasicDataset with energy as driver as you suggested in one of our meetings. Validation is failing with the following error:
`Traceback (most recent call last):
  File "./management/validation.py", line 393, in <module>
    main()
  File "./management/validation.py", line 379, in main
    comment = main_validation(dataset_paths)
  File "./management/validation.py", line 299, in main_validation
    qc_coverage = check_qcspec_coverage(data)
  File "./management/validation.py", line 199, in check_qcspec_coverage
    dataset.add_qc_spec(**spec)
TypeError: add_qc_spec() got an unexpected keyword argument 'maxiter'
`

**Comment by dotsdl** [comment]
Looks like we need a new release of `openff-qcsubmit` incorporating changes from [this commit](https://github.com/openforcefield/openff-qcsubmit/commit/828bcc837efd025b4a626311bb7aee3652f7d5c1). @jthorton do you plan to cut a new release fairly soon?

**Comment by dotsdl** [comment]
DF-CCSD(T)/CBS that will take up to 150 GiB of memory for 16 heavy atoms. Noting this here; will need workers specifically allocated for this.

**Comment by jthorton** [comment]
@pavankum please update with the master branch this should bring the validation back online.

**Comment by dotsdl** [comment]
Reviewing!

**Review by dotsdl — APPROVED** [review]
Looks great @pavankum! I made some small edits, and compressed the input torsiondrive pickle. Waiting on validation, then merging!

**Comment by pavankum** [comment]
> Looks great @pavankum! I made some small edits, and compressed the input torsiondrive pickle. Waiting on validation, then merging!

Thank you for the review @dotsdl !!

**Comment by dotsdl** [comment]
Ah shoot, meant to do a squash merge to keep out the big file. I think we'll be okay; may set this to the default for the repo. Thanks @pavankum!

**Comment by pavankum** [comment]
Apologies @dotsdl, I saw the validation pass and jumped the gun!

**Comment by pavankum** [comment]
@dotsdl looks like qcarchive-user-submit needs a bump in the qcsubmit version?

**Comment by jthorton** [comment]
@pavankum it looks like we have hit a bug in qcfractal here to do with the keyword alias, I think this is due to the specifications having capitalised names. I have made an [issue](https://github.com/MolSSI/QCFractal/issues/683) but this will require a new qcfractal release so maybe we should just lower the spec names in the dataset and try the submission again to get around this sooner?

**Comment by pavankum** [comment]
Thank you @jthorton, will make a new PR

**Comment by pavankum** [comment]
@dotsdl @jthorton moving this submission to backlog for now since it fails at the qca level, please archive or delete this PR since the new submission with lowercase keywords is at #227

**Pull request merged**
