### PR TITLE
Update to Nitrogen Grid Optimization jobs - geometries .json serializable

### PR DESCRIPTION
**Pull request by jmaat**
I made the geometries in the PR .json serializable. @dgasmith

### CODE REVIEW

**Comment by jmaat** [comment]
I made the geometries in the PR .json serializable. @dgasmith

**Comment by dgasmith** [comment]
Can you do the same thing for the molecule symbols? It is still pre-serialized JSON.

**Comment by jmaat** [comment]
Okay, just made the symbols .json serializable too. @dgasmith

**Comment by dgasmith** [comment]
Great, thanks! Just needs the conflict resolution and its good to go.

**Comment by jmaat** [comment]
@dgasmith Ok, resolved all conflicts.

**Pull request merged**
