### PR TITLE
1st round Gen 3 td dataset

### PR DESCRIPTION
**Pull request by hyejang**
- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset is named `dataset.json`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [ ] Make a new dataset entry in the mapping table, INDEX.md
- [ ] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
It would also be desirable to set the torsiondrive priority to 'high' for this dataset within the submission itself.

**Comment by hyejang** [comment]
Okay, @SimonBoothroyd, @dotsdl they are ready for review. Please note that there will be addition of torsiondrives (around ~400 new entries) to the dataset in one or two days.

**Review by trevorgokey — CHANGES_REQUESTED** [review]
This in general looks good, and looks like a fun dataset! The only thing I'd like to see is, due to the complexity of the dataset generation, is that the `long description` has a few sentences describing and briefly summarizing the intentions of this set of molecules, and how it was generated. For example, roughly where were initial molecule inputs derived from, and then how were they manipulated and filtered? What guided the selection of torsions to drive?

**Comment by hyejang** [comment]
@trevorgokey thanks for reviewing the dataset. Sure, that makes sense. I updated  `long_description` and added a detailed explanation on how the dataset was designed in `README.md`. Please let me know if there is anything unclear or missing.

**Review by dotsdl — APPROVED** [review]
Great work @hyejang! Items below:

1. Can we remove the file `4.select-torsions/tid_molecules_list.pdf`? The file is 24MB, over half the 45MB of the submission directory. I tried to compress it with no luck, and my PDF reader doesn't appear to render it. This will help us to keep the size of the repo from growing too fast.

That's it! Will merge after your response.

**Comment by hyejang** [comment]
Sure, since we have list of SMILES in `tid_molecules_list.p`, I think we are good to remove the pdf file. Thanks for reviewing it.

**Comment by dotsdl** [comment]
@trevorgokey are you satisfied?

**Comment by dotsdl** [comment]
I think we're good to go here, thank you @hyejang for addressing @trevorgokey's request!

**Comment by trevorgokey** [comment]
Just did a manual restart kick on this since some jobs did not seem to be touched.

**Comment by dotsdl** [comment]
Setting this to "Requires Scientific Review". No additional forward progress is being made on the remaining incomplete torsiondrives due to what now look like systematic errors.

@hyejang if the remaining errors are acceptable to you, we can also move to "Archived/Complete".

**Pull request merged**
