### PR TITLE
Add PEPCONF OptimizationDataset

### PR DESCRIPTION
**Pull request by jchodera**
@dotsdl @trevorgokey @JoshHorton : This is a conversion of the [PEPCONF](https://www.nature.com/articles/sdata2018310) dataset ([GitHub](https://github.com/aoterodelaroza/pepconf)) to SMILES for ingestion into our QCSubmit pipeline to generate an `OptimizationDataset` for @maxentile @yuanqing-wang. 

This dataset contains several categories of interesting short peptides:
* dipeptide
* tripeptide
* disulfide-linked peptides
* short bioactive peptides
* cyclic peptides

We should use our standard conformer enumeration schemes to generate conformers for QM.

Could someone take over submission from here?

Thanks!

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset is named `dataset.json`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Ready to submit!

### CODE REVIEW

**Comment by jchodera** [comment]
Would be awesome if we could get this going in the next couple of weeks!

**Comment by dotsdl** [comment]
Should be ready to go @jchodera! @jthorton, would you mind reviewing?

Some notes on choices:
- I have the `openeye-toolkit` in my environment with a license loaded, so this *should* have been used when calling `openforcefield.topology.Molecule.from_smiles`. This could be important given that the canonical isomeric SMILES @jchodera generated from the original XYZ files came from openeye as well, so this would be a roundtripping with it.
- I specified `rdkit` as the toolkit to use for enumerating stereoisomers, conformers in the workflow components. I drew this from @trevorgokey's use of these components in his CHO submission. Is there any reason to use `rdkit` over `openeye`, or vice-versa, here?

**Comment by trevorgokey** [comment]
This looks fantastic! Nice to see everything was transferable and made things easier.

This dataset shows that we might want to find a way to generate a pdf of the filtered molecules, since the final pdf only has the filtered molecules. We might want an easy way (a pdf) to see which molecules were filtered in the future. I'll keep this in mind for the next notebook/dataset I prepare.

**Comment by jchodera** [comment]
It this almost ready to launch? @yuanqing-wang and @maxentime are eager to start using the data in a week or so!

**Comment by dotsdl** [comment]
We have a molecule in this set with 58 conformations; this may be preferable if it's a big, flexible molecule, but it also means the dataset as a whole may take more time to compute. Thoughts @jchodera?

**Comment by jchodera** [comment]
This is intended! I'm surprised there are not more conformations!

This should still be quick compared to `TorsionDrive`, since all the optimizations are independent and can be effectively scheduled in parallel.

**Comment by dotsdl** [comment]
Great, thanks! @trevorgokey, if you can give this a review approval, we'll proceed with merge once the current QCA server issues are resolved.

**Review by trevorgokey — APPROVED** [review]
Looks good. I think in the future, it would be good to print out entries that were filtered in the notebook, so it is easy to reference. In this case, a few failed stereo enumeration. I was under the impression that this submission had all stereo defined, so this could be a bug somewhere. Here are the filtered molecules pulled from dataset.json.bz2, for easier reference:

```
      "molecules": [
        "[H][N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C]([H])([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[C]([H])([H])[S][S][C]([H])([H])[C@@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N+]([H])([H])[H])[N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C]([H])([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N+]([H])([H])[H]",
        "[H][c]1[c]([H])[c]([H])[c]([C]([H])([H])[C@@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N+]([H])([H])[H])[C]([H])([H])[C]([H])([H])[C](=[O])[O-])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N+]([H])([H])[H])[C]([H])([H])[c]2[c]([H])[c]([H])[c]([H])[c]([H])[c]2[H])[C]([H])([H])[C]([H])([H])[C](=[O])[O-])[C]([H])([H])[c]2[c]([H])[c]([H])[c]([H])[c]([H])[c]2[H])[C]([H])([H])[C]([H])([H])[C](=[O])[O-])[N]([H])[C](=[O])[C]([H])([H])[H])[c]([H])[c]1[H]",
        "[H][C]1=[C]([C]([H])([H])[C@@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[H])[C]([H])([H])[c]2[c]([H])[c]([H])[c]([H])[c]([H])[c]2[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[C]([H])([H])[C]2=[C]([H])[N]([H])[c]3[c]([H])[c]([H])[c]([H])[c]([H])[c]32)[N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C]([H])([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[c]2[c]([H])[c]([H])[c]([H])[c]([H])[c]2[N]1[H]",
        "[H][C]1=[N][C]([C]([H])([H])[C@@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C]([H])([H])[H])[C]([H])([H])[c]2[c]([H])[c]([H])[c]([H])[c]([H])[c]2[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[C]([H])([H])[C]2=[C]([H])[N]([H])[c]3[c]([H])[c]([H])[c]([H])[c]([H])[c]32)[C]([H])([H])[C]2=[C]([H])[N]([H])[c]3[c]([H])[c]([H])[c]([H])[c]([H])[c]32)=[C]([H])[N]1[H]",
        "[H][S][C]([H])([H])[C@@]([H])([C](=[O])[N]([H])[C]([H])([H])[C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N+]([H])([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N+]([H])([H])[H])[N]([H])[C](=[O])[C]([H])([H])[H]"
      ]
```

These molecules were in the PEPCONF csv, but were NOT submitted for calculation.

**Comment by dotsdl** [comment]
Thank you @trevorgokey. @jchodera I'm ready to merge and fire this one off today; are you okay with the filtered molecules? As Trevor pointed out, you can find this in the `dataset.json.bz2` as:

```
"filtered_molecules": {
    "EnumerateStereoisomers": {
      "component_name": "EnumerateStereoisomers",
      "component_description": {
        "component_name": "EnumerateStereoisomers",
        "component_description": "Enumerate the stereo centers and bonds of the molecule if possible.",
        "component_fail_message": "The molecules stereo centers or bonds could not be enumerated",
        "toolkit": "rdkit",
        "undefined_only": false,
        "max_isomers": 100,
        "rationalise": true
      },
      "component_provenance": {
        "OpenforcefieldToolkit": "0.8.0",
        "QCSubmit": "v0.1.0",
        "rdkit": "2020.09.1"
      },
      "molecules": [
        "[H][N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C]([H])([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[C]([H])([H])[S][S][C]([H])([H])[C@@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N+]([H])([H])[H])[N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C]([H])([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N+]([H])([H])[H]",
        "[H][c]1[c]([H])[c]([H])[c]([C]([H])([H])[C@@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N+]([H])([H])[H])[C]([H])([H])[C]([H])([H])[C](=[O])[O-])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N+]([H])([H])[H])[C]([H])([H])[c]2[c]([H])[c]([H])[c]([H])[c]([H])[c]2[H])[C]([H])([H])[C]([H])([H])[C](=[O])[O-])[C]([H])([H])[c]2[c]([H])[c]([H])[c]([H])[c]([H])[c]2[H])[C]([H])([H])[C]([H])([H])[C](=[O])[O-])[N]([H])[C](=[O])[C]([H])([H])[H])[c]([H])[c]1[H]",
        "[H][C]1=[C]([C]([H])([H])[C@@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[H])[C]([H])([H])[c]2[c]([H])[c]([H])[c]([H])[c]([H])[c]2[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[C]([H])([H])[C]2=[C]([H])[N]([H])[c]3[c]([H])[c]([H])[c]([H])[c]([H])[c]32)[N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C]([H])([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[c]2[c]([H])[c]([H])[c]([H])[c]([H])[c]2[N]1[H]",
        "[H][C]1=[N][C]([C]([H])([H])[C@@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C@@]([H])([N]([H])[C](=[O])[C]([H])([H])[H])[C]([H])([H])[c]2[c]([H])[c]([H])[c]([H])[c]([H])[c]2[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[C]([H])([H])[C]2=[C]([H])[N]([H])[c]3[c]([H])[c]([H])[c]([H])[c]([H])[c]32)[C]([H])([H])[C]2=[C]([H])[N]([H])[c]3[c]([H])[c]([H])[c]([H])[c]([H])[c]32)=[C]([H])[N]1[H]",
        "[H][S][C]([H])([H])[C@@]([H])([C](=[O])[N]([H])[C]([H])([H])[C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[C@]([H])([C](=[O])[N]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N+]([H])([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C]([N]([H])[H])=[N+]([H])[H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N+]([H])([H])[H])[N]([H])[C](=[O])[C]([H])([H])[H]"
      ]
    },
```

**Comment by jchodera** [comment]
Odd! These failures all contain Arg residues. Not sure why they failed, but it would be good to capture the input SMILES that fail enumeration since the output SMILES make it hard to see where things went wrong.

This should be super valuable without those failed molecules anyway!

**Comment by dotsdl** [comment]
Excellent, thanks @jchodera! We will consider an approach for making failures more identifiable in the output (e.g. input SMILES) and implement for future submissions. We'll launch this now!

**Comment by jchodera** [comment]
Wow, we've only some 100 optimizations in 24 hours? Perhaps I'm running the wrong kind of workers? Or maybe the preemptable jobs are the problem?

**Comment by dotsdl** [comment]
I have asked @trevorgokey to experiment with worker numbers on his resources to try and reduce the frequency of pre-emption. I have also reworked our deployment on PRP to reduce the likelihood of memory issues. In addition, I am working to upgrade the priority of this dataset to "high". This should help it to advance faster in the presence of other datasets in our compute queue.

We will monitor over the next few days to see if this improves the rate of success on this dataset. We can re-assess on Monday if progress still appears slower than expected.

**Comment by jchodera** [comment]
Hm, 12 QM calculations successfully completed in 24 hours seems to suggest something is pathologically wrong here.

**Comment by dotsdl** [comment]
I've moved this to "Requires Scientific Review" due to the high error rate we are seeing. INCOMPLETE Optimizations will continue to be taken up by compute managers, but ERRORs will not be restarted. Investigation into these high error rates, as well as what could be done to reduce them, would give informative next steps for a dataset like this.

**Pull request merged**
