### PR TITLE
[WIP] Genentech set 3, torsiondrives

### PR DESCRIPTION
**Pull request by pavankum**
- [x] Created a new folder in the submissions directory containing the dataset
- [ ] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [ ] All files used to produce the dataset are included with a description
- [ ] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [ ] Dataset is named `dataset.json`
- [ ] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [ ] QCSubmit validation passed
- [ ] Make a new dataset entry in the mapping table, INDEX.md
- [ ] Ready to submit!

### CODE REVIEW

**Comment by pavankum** [comment]
@JoshHorton or @dotsdl 
(this is not urgent)
when any of you have a moment please check the submission notebook and comment, this is for torsiondrives from genentech set of molecules, I got some python recursion errors, may be due to wrong calls(?). Also, please advise on the maximum number of conformers and stereoisomers to use for torsiondrives.

**Comment by dotsdl** [comment]
@jthorton thoughts?

**Comment by pavankum** [comment]
@jthorton & @dotsdl it's a false alarm, I had a trivial mistake in my code
`qcs_ds.create_dataset(` \
`dataset_name`
instead of 
`qcs_ds.create_dataset(dataset_name`
Apologies for not reading the error properly

**Comment by pavankum** [comment]
@dotsdl this was put on hold because of Iodine containing molecules, I think this is good to go now, no hurry though.

**Pull request closed without merging**
