### PR TITLE
OpenFF Substituted Phenyl Set 1 v2.0

### PR DESCRIPTION
**Pull request by dotsdl**
This is a resubmission of the `OpenFF Substituted Phenyl Set 1 v1.0`, in response to metadata not being [stored in the places we need](https://github.com/openforcefield/qca-dataset-submission/pull/140#issuecomment-705675738) to use the dataset for MM reliably.

I have:
1. Used the original conformers, with no interpretation or conformer generation with the `openforcefield` toolkit. If you are reviewing, can you please confirm the approach taken matches this intention?
2. Removed molecules that we could not get to SCF-converge in the original set. These all include iodine, though other iodine-including molecules did not fail to SCF-converge. I tried to get these molecules to converge with up to `maxiter=3200` on local infrastructure to no avail. These molecules are:
    - `CC[CH2:4][NH:3][c:2]1ccnc([cH:1]1)I`
    - `C[C:4](=O)[NH:3][c:2]1[cH:1]cnc(c1)I`
    - `[CH3:4][O:3][c:2]1[cH:1]cnc(c1)I`

----

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset is named `dataset.json`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
@trevorgokey or @jthorton, would one of you be willing to review this submission?

**Comment by dotsdl** [comment]
Should probably split out the MM compute as a separate submission PR; won't pass validation until the dataset itself is up on public QCArchive.

**Comment by jthorton** [comment]
You can also role them into the submission dataset and validation should pass, also do we need both 1.2.1 and 1.2.0? Apart from that this looks really good.

**Comment by dotsdl** [comment]
I think there were some improvements to the FF in 1.2.1 compared to 1.2.0? It may not be a change that will impact this dataset, though. @jmaat thoughts?

**Comment by dotsdl** [comment]
Supplemental compute is now a separate submission: #161.

**Comment by dotsdl** [comment]
Awesome, thanks @jthorton! Does this constitute a review? :wink: 

If so, and If you approve, can you give me a green check mark?

**Review by jthorton — CHANGES_REQUESTED** [review]
Thanks for putting this together its looking good I just have a few comments. 
- I think we should be okay to include all iodine-containing molecules, I have tested the ones you highlighted using the dev psi4 version we will be rolling out to the managers and the single points converge in around 11-15 SCF iterations, can you check which version of psi4 you are using in your testing? 
- We can also probably use a lower SCF max in this case. 
- I think your method of moving the molecules by will should be enough to make sure that the molecule is considered unique by QCArchive but to be sure we can check this by looping over all of the molecules and getting the hash using `get_hash()` then query the public QCArchive using `client.query_molecules(molecule_hash=hash)` this should be an empty list if the deduplication has worked.
- It is possible to role the MM compute into this submission as well and have it validated but this would link the error cycling together which I don't think is a bad idea as we expect the MM to sail through.
- 1.2.1 was a bond force fix for `b24` and `b27` which according to the coverage report for this dataset is not exercised so I would just use either 1.2.1 or 1.2.0 as they should be the same.

**Comment by dotsdl** [comment]
Thanks @jthorton!

I re-ran my local torsiondrives of the three problem molecules with `psi4` version `1.4a2.dev1058+670a850` (what we are now using in production as of yesterday). However, I get the same result for each:

```
geomeTRIC run_json error:
Traceback (most recent call last):
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib/python3.7/site-packages/geometric/run_json.py", line 225, in geometric_run_json
    geometric.optimize.Optimize(coords, M, IC, engine, None, params)
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib/python3.7/site-packages/geometric/optimize.py", line 1331, in Optimize
    return optimizer.optimizeGeometry()
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib/python3.7/site-packages/geometric/optimize.py", line 1298, in optimizeGeometry
    self.calcEnergyForce()
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib/python3.7/site-packages/geometric/optimize.py", line 1002, in calcEnergyForce
    spcalc = self.engine.calc(self.X, self.dirname)
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib/python3.7/site-packages/geometric/engine.py", line 873, in calc
    return self.calc_new(coords, dirname)
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib/python3.7/site-packages/geometric/engine.py", line 865, in calc_new
    raise QCEngineAPIEngineError("QCEngineAPI computation did not execute correctly. Message: " + ret["error"]["error_message"])
geometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Unknown Error: Traceback (most recent call last):
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib//python3.7/site-packages/psi4/driver/schema_wrapper.py", line 401, in run_qcschema
    ret_data = run_json_qcschema(input_model.dict(), clean, False, keep_wfn=keep_wfn)
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib//python3.7/site-packages/psi4/driver/schema_wrapper.py", line 548, in run_json_qcschema
    val, wfn = methods_dict_[json_data["driver"]](method, **kwargs)
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib//python3.7/site-packages/psi4/driver/driver.py", line 717, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib//python3.7/site-packages/psi4/driver/procrouting/proc.py", line 2356, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib//python3.7/site-packages/psi4/driver/procrouting/proc.py", line 2261, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib//python3.7/site-packages/psi4/driver/procrouting/proc.py", line 1541, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib//python3.7/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 93, in scf_compute_energy
    raise e
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib//python3.7/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 86, in scf_compute_energy
    self.iterations()
  File "/home/david/.conda/envs/qcarchive-worker-openff-psi4-2/lib//python3.7/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 464, in scf_iterate
    raise SCFConvergenceError("""SCF iterations""", self.iteration_, self, Ediff, Dnorm)
psi4.driver.p4util.exceptions.SCFConvergenceError: Could not converge SCF iterations in 3200 iterations.
```
This is on Linux; is it possible we're seeing some platform-dependence here?

**Comment by dotsdl** [comment]
Removed openff 1.2.0 in #161 per your suggestion @jthorton.

**Comment by dotsdl** [comment]
@jthorton added a hash check of each molecule against public QCA to the preparation notebook. All clear! Thank you for this idea!

**Comment by dotsdl** [comment]
@jmaat are the excluded molecules below vital to your work?
- `CC[CH2:4][NH:3][c:2]1ccnc([cH:1]1)I`
- `C[C:4](=O)[NH:3][c:2]1[cH:1]cnc(c1)I`
- `[CH3:4][O:3][c:2]1[cH:1]cnc(c1)I`

We are not able to get geometry optimizations of these molecules due to SCF convergence issues, despite even setting an SCF `maxiter=3200`. If they are not vital, we can proceed without them.

**Comment by jmaat** [comment]
@dotsdl 
We can skip them for now, but take note that they are missing from the dataset. 
This dataset was as per request of @ChayaSt... we wanted to have the datasets in the figures stored in QCA for the wbo publication.

**Comment by ChayaSt** [comment]
@jmaat  and @dotsdl, because of the SCF convergence issues with Iodine, I ended up skipping that series from the paper. It's fine if we don't have it in this dataset.

**Comment by jmaat** [comment]
@ChayaSt Thanks

**Comment by dotsdl** [comment]
Awesome, thank you @ChayaSt! We'll proceed!

**Comment by dotsdl** [comment]
@jthorton could I get your final blessing for the green badge? :grin:

**Comment by jmaat** [comment]
@dotsdl great, thanks

**Pull request merged**
