### PR TITLE
OpenFF Industry Benchmark Season 1

### PR DESCRIPTION
**Pull request by jthorton**
- [X] Created a new folder in the submissions directory containing the dataset
- [X] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [X] All files used to produce the dataset are included with a description
- [X] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [X] Dataset is named `dataset.json`
- [X] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [ ] Make a new dataset entry in the mapping table, INDEX.md
- [ ] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
Great work @jthorton! Thank you for assembling this dataset!

It's perfectly crafted and beautifully presented. Well done!

**Review by dotsdl — APPROVED** [review]
Great work @jthorton! Thank you for assembling this dataset!

It's perfectly crafted and beautifully presented. Well done!

**Comment by jthorton** [comment]
@dotsdl Looks like the dataset is too large to call save on or I might have the error wrong, Ill look into the archive and see if any of the dataset has made it in.

**Comment by dotsdl** [comment]
Switched priority to `normal`, as many of the remaining errors are likely systematic due to nonexplicit hydrogens on the MRK set.

**Comment by dotsdl** [comment]
We will cease error cycling on this set.

**Pull request merged**
