### PR TITLE
update validation env to include openmm

### PR DESCRIPTION
**Pull request by pavankum**
Update validation env to include openmm and pin pint to < 0.20.

### CODE REVIEW

**Comment by dotsdl** [comment]
Why `pint` < 0.20? Can you elaborate?

**Review by dotsdl — APPROVED** [review]
Accepting this for now; we'll hopefully be able to drop `openmm` as a dependency again here once openforcefield/openff-qcsubmit#204 is merged.

**Comment by pavankum** [comment]
> Why pint < 0.20? Can you elaborate?

Just as a precaution for the recent changes in pint that may affect openff-units.

**Comment by pavankum** [comment]
@dotsdl This change is causing the validation failure, https://github.com/python/importlib_metadata/pull/405, `entry_points()` is a dict now. The failure point is https://github.com/openforcefield/openff-toolkit/blob/main/openff/toolkit/typing/engines/smirnoff/forcefield.py#L86. We have to pin to 4.11.4 for now.

**Comment by pavankum** [comment]
On second thoughts, it looks like a bad environment resolution by conda (or mamba) on the validation CI

```
importlib-metadata        5.0.0              pyha770c72_1    conda-forge
importlib_metadata        1.5.0                    py38_0    conda-forge
```



When I test locally if both are `5.0.0` it works,
```
importlib-metadata        5.0.0              pyha770c72_1    conda-forge
importlib_metadata        5.0.0                hd8ed1ab_1    conda-forge
```

**Comment by pavankum** [comment]
pinning it in #320

**Pull request merged**
