### PR TITLE
OpenFF Protein Capped 1-mers 3-mers Optimization

### PR DESCRIPTION
**Pull request by chapincavender**
Optimization dataset for protein capped 1-mers Ace-X-Nme and capped 3-mers Ace-Y-X-Y-Nme with Y = {Ala, Val} and X = 26 canonical amino acids with common protomers/tautomers (Ash, Cyx, Glh, Hid, Hip, and Lyn)

## New Submission Checklist

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Made a new dataset entry in the mapping table in repository `README.md`
- [x] Ready to submit!

### CODE REVIEW

**Review by pavankum — APPROVED** [review]
Thank you for putting this together @chapincavender! LGTM! One minor question, is there a reason to not enumerate protonation states?
Edit: Never mind, got it, "X = 26 canonical amino acids with common protomers/tautomers"

**Comment by pavankum** [comment]
@dotsdl there might be some config issues with the remaining 4 jobs, we're getting the same error upon resubmission, do you think we can retag and submit to a separate queue?

**Comment by dotsdl** [comment]
Can do, switched compute tag to `openff-vulkan` to route remaining tasks to my host here. This machine tends to be pretty reliable in terms of success rate.

**Comment by pavankum** [comment]
Thanks a lot @dotsdl :)

**Comment by pavankum** [comment]
Moving this to end of life, remaining 3 failed to converge in geometry optimization.

**Pull request merged**
