### PR TITLE
Multi-Br ESP dataset

### PR DESCRIPTION
**Pull request by lilyminium**
New submission testing the new QCSubmit version.

## New Submission Checklist

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Made a new dataset entry in the mapping table in repository `README.md`
- [x] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
Awesome, thanks for making this @lilyminium! I'll get started on #331 to fix the validation CI first so we can get its reporting.

**Comment by dotsdl** [comment]
@lilyminium getting the following when fetching this branch:

```
Switched to a new branch 'multi-br-v1.0'
Encountered 1 file that should have been a pointer, but wasn't:
	submissions/2023-11-02-OpenFF-multi-Br-ESP-Fragment-Conformers-v1.0/dataset.json.bz2
```

Can you check that you have `git-lfs` installed? It should be the case that on commit and push a smudge file gets created in the place of the actual file. It won't matter too much for this case (`dataset.json.bz2` is only 184kB), but does help to keep the size of the repo down over time.

**Comment by lilyminium** [comment]
Yes sorry, you're right, I did this on lilac where I did not have git-lfs installed. Ah... I re-committed and pushed on my laptop with lfs, which I *think* was supposed to fix it, but I'm not familiar enough with lfs to check 😅

**Comment by dotsdl** [comment]
@lilyminium all good! It now shows up as an LFS file in the diff:
image

**Comment by dotsdl** [comment]
@lilyminium looks like we have validation working again! Can you check to see what it's giving makes sense to you? I'm checking myself as well.

**Comment by lilyminium** [comment]
Thank you @dotsdl! All the validation properties look good on my end that I can tell.

**Review by dotsdl — APPROVED** [review]
Looks great @lilyminium! Merging!

**Comment by dotsdl** [comment]
Working on fixing the above submission failures today.

**Comment by dotsdl** [comment]
@jthorton raised that we likely don't want wavefunctions for each optimization of this set. I'm working on the submission infrastructure still, so we could revise this before it makes its way to QCArchive.

I've asked @bennybp if we can now get wavefunctions for only the final structure for the optimization; in the past this wasn't possible, but not sure if this has changed.

**Pull request merged**
