### PR TITLE
Nagl2 esp timing benchmark

### PR DESCRIPTION
**Pull request by amcisaac**
## New Submission Checklist

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Made a new dataset entry in the mapping table in repository `README.md`
- [x] Ready to submit!

## Compute Expansion Checklist

- [ ] Compute expansion filename matches pattern `compute*.json`; may feature a compression extension, such as `.bz2`
- [ ] QCSubmit validation passed
- [ ] Ready to submit!

### CODE REVIEW

**Review by lilyminium — COMMENTED** [review]
Generally LGTM -- thanks @amcisaac! Could you please add an entry to the overall README?

**Comment by amcisaac** [comment]
On my end it looks like I updated it, but maybe I added it to the wrong place? I put it at the end of `Basic Datasets`
Screen Shot 2024-09-16 at 5 28 05 PM

**Comment by lilyminium** [comment]
Ah sorry my bad -- I completely missed it. LGTM!

**Review by lilyminium — APPROVED** [review]

**Comment by lilyminium** [comment]
Oh dear. FWIW the `--- Too many errors; truncated here ---` is a QCA message -- querying the QCPortal should pull down actual output for more helpful diagnosis.

**Comment by amcisaac** [comment]
Looks like Psi4 can't do VV10 dipole polarizabilities, causing all the calculations to crash, based on the error `Fatal Error: Vx: RKS cannot compute VV10 Vx contribution.`

I just copied the list of properties from the MLPepper dataset since I figured it couldn't hurt--Do we need/want the dipole polarizabilities? Josh mentioned they included that because they are looking into a polarizable charge model, which to my knowledge we aren't working on. Happy to either 1) re-submit without requesting that or 2) change functional if we do

**Comment by j-wags** [comment]
Ah, the MLPepper dataset ran with psi4 1.9 and needed an additional dependency (pyddx). So these were probably crashing because they were landing on our `openff`-label workers, which (I assume) for provenance reasons have psi4 1.8 and no pyddx. 

We did the MLPepper dataset on the `isambard` tag so I could ensure that only workers with newer deps accept those tasks. 

So we'll want to retag this set and try sending it to newer workers made using the `psi4-ddx` image.

I'll give this a shot right now but am just heading offline for the week, so apologies if I leave it in a messy state.

**Comment by amcisaac** [comment]
This doesn't have ddx, so I think the reason is due to the VV10 gradients not being implemented (as mentioned [here](https://forum.psicode.org/t/sapt-dft-wb97x-v-error/1342)), which means we can't calculate the dipole polarizabilities. We're going to re-submit with PBE0

**Comment by amcisaac** [comment]
That's good to know though, as the next step is to submit a version with ddx for solvent!

**Comment by j-wags** [comment]
Ah, nice. Thanks for the clarification, I'll keep an eye open for your resubmission.

**Pull request merged**
