### PR TITLE
Added MM compute specs to CHO sandbox dataset

### PR DESCRIPTION
**Pull request by dotsdl**
- [ ] Created a new folder in the submissions directory containing the dataset
- [ ] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [ ] Dataset is named `dataset.json`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
This compute is ready for review! I used the same set of MM compute we are planning to use for benchmarking here.

**Review by jthorton — APPROVED** [review]

**Comment by dotsdl** [comment]
@jthorton I think we'll need to be able to pass through `overwrite=True` to the submit method for a dataset. We're getting failure here because on merge the first submission took longer than the 6 hour max allowed for a GH Action job. In order to try again, we'll need to be able to `ds.submit(overwrite=True)` in lifecycle, I believe.

**Comment by jthorton** [comment]
It looks like all of the specs were added but no tasks were generated maybe the compute call timed out? I am not sure if we want the ability to overwrite specs as this would lead to the db inconsistency that ben mentioned. I think in this case we just want to check if the spec we are adding is already there and if it is then run the compute call else throw an error to tell the user that this spec is already present and does not match so it needs to be added with a new name?

**Comment by jthorton** [comment]
@dotsdl This QCSubmit issue is now fixed, however, we still see a time out when generating the tasks ~36k tasks in this submission I think the only way to get this through is to split each MM compute spec into separate PRs/actions.

**Pull request merged**
