### PR TITLE
OpenFF Industry Benchmark Season 1 v1.1

### PR DESCRIPTION
**Pull request by dotsdl**
## New Submission Checklist

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [ ] Made a new dataset entry in the mapping table in repository `README.md`
- [x] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
@jthorton could you check my work here? I took the v1.0 dataset, excised the `MRK` optimizations, and replaced them with new ones generated from the explicit-hydrogen set included under `merck`. The `merck/refdata.json/bz2` was prepared using the [Season 1 protocol](https://openforcefield.atlassian.net/wiki/spaces/PS/pages/971898891/Optimization+Benchmarking+Protocol+-+Season+1) through step 3.

Thank you!

**Review by jthorton — APPROVED** [review]
LGTM! Let's hope the deduplication works, and do you also need to add on the MM specifications with this submission?

**Comment by dotsdl** [comment]
@jthorton thank you! I'll do MM spec addition as a separate PR so it can be managed independently (compute spec, priority, etc.).

**Comment by dotsdl** [comment]
This dataset is probably about as complete as it will get. Will let go for up to a week longer, then mark as Archived/Complete.

**Comment by dotsdl** [comment]
No longer progressing, remaining errors appear systematic. Moving to *Archived/Complete*.

**Pull request merged**
