### PR TITLE
Coverage Hessian Submission

### LINKED ISSUE #33: submit hessian jobs for the coverage set of molecules
The optimizations for the coverage set of molecules were submitted in
https://github.com/openforcefield/qca-dataset-submission/tree/master/2019-06-25-smirnoff99Frost-coverage

We want to submit hessian calculation for the optimized geometries. 
The simplest way is to submit one hessian computation for each optimization record. The downside is that it is possible there are duplications in the optimized geometries, and we will most likely not use all of the data in fitting.

Since we are more interested in the hessian of the global minimum of each molecule, we can pick the lowest energy structure for each molecule out of the optimized geometries, and just submit hessian jobs for those. This will greatly reduce the total cost of this dataset.

### PR DESCRIPTION
**Pull request by dgasmith**
Submits coverage set, closes #33.

### CODE REVIEW

**Comment by yudongqiu** [comment]
Thanks for making this submission quick. My understanding is that this is a temporary solution for the Hessian calculations, because it creates a general `Dataset`, that does not have "entry" and "attributes". In the future we might want to refactor this when `HessianDataset` is available, which supports `add_entry()`, `gen_entry()` and the entries should have attributes such as `cmiles_ids`.

BTW, I think this PR also contains changes in the file `2019-07-05 eMolecules force field discrepancies 1/02_create_optimization_dataset.py`, is that intended?

**Comment by dgasmith** [comment]
I don't think we will make a HessianDataset as there are no changes required to the code to support energy/gradient/Hessian/property single computations within the Dataset class. We can certainly expand the Dataset class to work similarly to the ProcedureDataset classes like Optimization/TorsionDrive/etc.

Yes, the update to eMolecules was intended here.

**Comment by yudongqiu** [comment]
Sure sounds good. I think if the `Dataset` class is expand to support the `add_entry()` and `get_entry()` methods, that would be enough for the hessian jobs.

**Comment by davidlmobley** [comment]
Is this ready to go now?

**Comment by yudongqiu** [comment]
> Is this ready to go now?

I believe this is already submitted and running on the server.

**Comment by dgasmith** [comment]
Just need an approval and merge.

**Comment by davidlmobley** [comment]
OK, merging!

**Pull request merged**
