### PR TITLE
Patch lifecycle to avoid interacting with project boards overly

### PR DESCRIPTION
**Pull request by lilyminium**
This PR patches lifecycle.py to give up on moving things between board columns and just submit the datasets. It's meant to be a temporary, easier to review fix than #377.

### CODE REVIEW

**Comment by lilyminium** [comment]
Apologies for the messy dangerbot actions -- I refactored lifecycle.py to use GraphQL, but then split that out into a separate PR #376. This is now just a bandaid patch to try to get datasets submitted before #376 can get merged. We will have to manually move the card to the Error cycling to get that to trigger, I believe.

**Comment by lilyminium** [comment]
The passing CI run was triggered manually here: https://github.com/openforcefield/qca-dataset-submission/actions/runs/10807416097/job/29978159402

**Comment by lilyminium** [comment]
I think this is now ready for review.

**Review by j-wags — APPROVED** [review]
Looks great, thanks for updating this and apologies that this held up submissions!

**Comment by lilyminium** [comment]
Thanks for the review @j-wags!

**Pull request merged**
