### PR TITLE
Add two torsiondrive datasets (OpenFF Group1 Torsions 2, SMIRNOFF Coverage Torsion Set 2)

### PR DESCRIPTION
**Pull request by hyejang**
`2020-01-28-OpenFF-Group1-Torsions-2`: For dataset, `OpenFF Group1 Torsions 2`, containing 4 1-D torsions for the newly defined torsion terms, t51a and t51b. Input molecule set used for generation is Roche set, which was used for `OpenFF Group1 Torsions` dataset generation. 

`2020-01-28-smirnoff99Frost-coverage-torsion-2`: For dataset, `SMIRNOFF Coverage Torsion Set 2`, containing 7 1-D torsions for the newly defined torsion terms, t51a and t51b. Input molecule set used for dataset generation is coverage set, which was used for `SMIRNOFF Coverage Torsion Set 1` dataset generation.

### CODE REVIEW

**Comment by dgasmith** [comment]
You had asked me to hold off on submitting this. Is this ready to go now?

**Comment by hyejang** [comment]
It will be ready soon.(maybe in 30 min) Would it be okay if I ask your review when it is good to go?

**Comment by dgasmith** [comment]
Of course! Just ping me here when you are ready.

**Comment by hyejang** [comment]
@dgasmith the dataset is ready to go! Thanks for waiting.

**Comment by dgasmith** [comment]
Submitted, please note the new template that I use for submission. I have updated master to reflect canonical changes.

**Pull request merged**
