### PR TITLE
Update constrained opts of mp2-heavy-aug-cc-pvtz

### PR DESCRIPTION
**Pull request by pavankum**
## Updated Submission Checklist

- [x] Updated `README.md` describing the change 
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [ ] Made a new dataset entry in the mapping table in repository `README.md`
- [x] Ready to submit!

### CODE REVIEW

**Comment by pavankum** [comment]
looks like even the MP2 spec data is useless since the constrained opts are not aligned properly with the torsion scans, this may be discarded, will keep it on hold for now, no need to review this one yet

**Comment by dotsdl** [comment]
No problem @pavankum. Happy to review when you've got a dataset you'd like submitted!

**Comment by pavankum** [comment]
> looks like even the MP2 spec data is useless since the constrained opts are not aligned properly with the torsion scans, this may be discarded, will keep it on hold for now, no need to review this one yet

Note to self: the mistake with misalignment is due to bad angle index matching, somehow the constrained structures correspond to different ones after the creation of new dataset, easy way to find them is to measure the dihedral angle from the geometries.

**Comment by pavankum** [comment]
Hi @dotsdl , when you have time can you review and push this through. This includes addition of 23 x 24 new constrained opts on top of the current 36 x 24 set. These will be faster and do not consume much time since they're single optimizations. I had rerun the notebook with few updates to the qcsubmit invocations, so the dataset file created includes the previous constrained opts that are already calculated, I am assuming these would be filtered out at the QCA server level as duplicates (correct me if I am wrong).
This is supposed to be an alternative to the full mp2 torsion scans I submitted in #217 , the other set might become redundant but I still want to confirm a few cases that show completely different torsion profiles so I am still inclined to let them run.

**Comment by dotsdl** [comment]
Can do! Probably can get this in tomorrow morning!

**Comment by dotsdl** [comment]
@pavankum we should set the version in the dataset name to `v1.1`, since this amounts to an expansion of the previous set. Can you also put a note on what the `v1.1` version includes, expanding on the `v1.0` version?

**Comment by pavankum** [comment]
@dotsdl Thank you for the review! I just pushed those changes, one quick question, if I remade the dataset.json with additional molecules the old calculations would be marked as duplicate at the server level and won't be calculated again, right?

**Comment by dotsdl** [comment]
> @dotsdl Thank you for the review! I just pushed those changes, one quick question, if I remade the dataset.json with additional molecules the old calculations would be marked as duplicate at the server level and won't be calculated again, right?

Should be, are they completely unchanged? 

I'm going to to put the original `dataset.json` in place and name the new one `dataset-v1.1.json`. I'm also going to rename the original `QCSubmit_workflow_v1.ipynb` back to `QCSubmit_workflow.ipynb`, and ditto for the other files. In the future I think we should avoid renaming files from previous submissions where possible, and only add files when making new iterations.

**Comment by dotsdl** [comment]
@pavankum is the `torsiondrive_data.pickle` necessary? If not, I'll remove it!

**Comment by pavankum** [comment]
@dotsdl yeah, they're unchanged, I hope the change in qcsubmit version wouldn't introduce anything new in those records. 

> we should avoid renaming files from previous submissions where possible, and only add files when making new iterations.

Sure, I will keep that in mind for future submissions, sorry about that.

> is the torsiondrive_data.pickle necessary? If not, I'll remove it!

I think we can remove that, we are not reading it again, I just used the old submission script.

**Comment by dotsdl** [comment]
Awesome, thanks @pavankum! Finishing up my review. The diff is a lot easier to view now! Thank you!

**Comment by pavankum** [comment]
Thank you @dotsdl :)

**Review by dotsdl — APPROVED** [review]
Looking good @pavankum! Sorry for the delay; submitting!

**Pull request merged**
