### PR TITLE
OpenFF BCC Refit Study COH v1.0

### PR DESCRIPTION
**Pull request by SimonBoothroyd**
- [X] Created a new folder in the submissions directory containing the dataset
- [X] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [X] All files used to produce the dataset are included with a description
- [X] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [X] Dataset is named `dataset.json`
- [X] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Ready to submit!

### CODE REVIEW

**Comment by trevorgokey** [comment]
As an update; we might be able to unblock this, including not relying on software updates, as long as we are able to handle the data that the current wavefunction protocols provide. We will need to confirm that, roughly, `Da = C[:,nalpha]*C[:,nalpha].T`. Currently we are waiting/trying/seeking to store `Da`, but current working versions store `C`, which should be enough as long as everything looks correct.

**Comment by jthorton** [comment]
As this dataset will also need a PCM spec latter we should not submit this until QCSubmit is updated to force c1 symmetry!

**Comment by dotsdl** [comment]
@jthorton can you re-roll this dataset with the changes it needs? Should be ready for submission!

**Comment by dotsdl** [comment]
@trevorgokey I think this one is ready for a final review!

**Comment by SimonBoothroyd** [comment]
> As this dataset will also need a PCM spec latter we should not submit this until QCSubmit is updated to force c1 symmetry!

@jthorton is this in place now?

**Review by jthorton — APPROVED** [review]

**Review by trevorgokey — APPROVED** [review]
Everything looks good! Thanks @jthorton for giving this another check

**Comment by dotsdl** [comment]
@SimonBoothroyd I cannot get the last `resp2-water` result to converge successfully, even with 2000 SCF iterations. Is this vital?

**Pull request merged**
