### PR TITLE
Add version 2 of the benchmark ligand fragments

### PR DESCRIPTION
**Pull request by jthorton**
## New Submission Checklist
- [X] Created a new folder in the submissions directory containing the dataset
- [X] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [X] All files used to produce the dataset are included with a description
- [X] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [X] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [X] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Made a new dataset entry in the mapping table in repository `README.md`
- [x] Ready to submit!

# Info
This PR updates the `OpenFF-benchmark-ligand-fragments-v1.0` to version 2 by supplementing the dataset with new fragments produced using the reworked fragmenter with both the openeye and ambertools back ends.

### CODE REVIEW

**Comment by jthorton** [comment]
@dotsdl this is now ready for review, the failing validation is due to missing element coverage in ani2x so some runs are expected to fail.

**Comment by dotsdl** [comment]
Reviewing!

**Review by dotsdl — APPROVED** [review]
Looks great @jthorton! Sorry for the delay from me in reviewing. Merging!

**Comment by dotsdl** [comment]
Removing `tracking` label for now; unfinished `xtb` tasks appear systematic. @jthorton do you have ANI workers going for the `openff-fragments` compute tag?

**Comment by jthorton** [comment]
Thanks @dotsdl, I plan to dive into the xtb failures next and currently no ani workers as they keep running out of memory ill try and submit some with more.

**Comment by dotsdl** [comment]
@jthorton looks like the remaining errors may be systematic? Do we have hypotheses for the observed `gfn0xtb` and `gfnff` errors?

**Comment by jthorton** [comment]
@dotsdl yes @pavankum has reported the gfn-ff issue [here](https://github.com/grimme-lab/xtb/issues/539), i suspect its similar for gfn0-xtb but we need to confirm.

**Comment by awvwgk** [comment]
GFN0-xTB probably fails due to not finding the parameter file in the environment, see https://github.com/grimme-lab/xtb/issues/384.

**Pull request merged**
