### PR TITLE
OpenFF Protein Dipeptide 2-D TorsionDrive v2.0

### PR DESCRIPTION
**Pull request by chapincavender**
## New Submission Checklist

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Made a new dataset entry in the mapping table in repository `README.md`
- [x] Ready to submit!

### CODE REVIEW

**Comment by pavankum** [comment]
@chapincavender Thanks for building the expanded dataset, this looks great! One minor thing, validation checks any file with `dataset*.json`, we may need to rename v1.0 file so as to avoid duplicate submission, @dotsdl when you have a moment can you please take a look and confirm.

**Comment by dotsdl** [comment]
@pavankum is right; the PR-based automation we use relies on the list of files the PR changed for identifying its `dataset*.json.*` files. We don't want it to try and submit the "new" `dataset-v1.0.json.bz2` file alongside the `2.0` file.

I've gone ahead and switched the name back for that historical artifact. @chapincavender is this okay with you? We'll be clear to merge if so!

**Comment by chapincavender** [comment]
Thanks for catching that @pavankum and @dotsdl. I wanted to rename the file so that in the future it's clear which version of the dataset is the most recent, but we can do that after this calculation completes. I think this is good to go.

**Review by pavankum — APPROVED** [review]

**Comment by pavankum** [comment]
(Not urgent!) @chapincavender when you have a moment can you please check whether scratch space is filling up on a node, thank you!

**Comment by chapincavender** [comment]
@pavankum The errors from "No space left on device" came from one manager on TSCC, but there have been no errors on that node since 9 pm yesterday. I'm going to leave this manager running for now, but I'll continue to monitor and shut it down if the errors return.

**Pull request merged**
