### PR TITLE
OpenFF Amide Torsion Set v1.0

### PR DESCRIPTION
**Pull request by SimonBoothroyd**
- [X] Created a new folder in the submissions directory containing the dataset
- [X] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [X] All files used to produce the dataset are included with a description
- [X] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [X] Dataset is named `dataset.json`
- [X] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Make a new dataset entry in the mapping table, INDEX.md
- [ ] Ready to submit!

### CODE REVIEW

**Review by trevorgokey — APPROVED** [review]
Looks good! It could be submitted as-is, but I have one suggestion.

Using only one conformation can give situations where SCF or optimization can fail to converge on that one molecule conformation (from the MM-based toolkit), killing the entire TD. To get around this, I'd jump the number of conformers up so that there is a better chance that at least one will optimize successfully. The TD will then take the successful optimizations, and proceed with the wavefront. This was the reasoning as to why I used 10 confs with an RMS of 0.1 in the WBO set.

The fact that the mean confs is 1.26 tells me that a single molecule has two TDs, and qcsubmit has combined them into a single molecule object, even though there will be two separate TD services.

**Review by jthorton — APPROVED** [review]
I agree with @trevorgokey I think expanding conformers would be wise here there is a [component](https://github.com/openforcefield/openff-qcsubmit/blob/45e716e3cc70ee05614fbe951c627efc6d9eec84/openff/qcsubmit/workflow_components/conformer_generation.py#L15) to do this in parallel. Note that due to how deduplication works the conformers produced may be different from what you have generated here.

**Review by dotsdl — APPROVED** [review]
Fantastic @SimonBoothroyd! This is a clean, clear submission. Thanks for putting it together.

**Comment by SimonBoothroyd** [comment]
@jthorton @trevorgokey @dotsdl these still seem to be erroring - can one you take a quick look when you get a chance?

**Comment by trevorgokey** [comment]
There were still 581 optimization errors after a manual GHA, so I just restarted this dataset using local tools. It looks like the GHA is missing some optimizations to restart.

**Comment by SimonBoothroyd** [comment]
Thanks @dotsdl - I think what's finished is fine so maybe just move to "Archived/Complete"

**Pull request merged**
