### PR TITLE
[WIP] Add an "informative" set from Jordan Ehrman

### PR DESCRIPTION
**Pull request by davidlmobley**
This begins adding an "informative" set of molecules (as an optimization dataset, but may also want torsion drives eventually) as discussed in #46 . This is a placeholder PR to get the molecule set and visualization of it up online. @jchodera is going to be preparing some datasets for submission this weekend and hopefully this is one of the ones he can prepare.

### CODE REVIEW

**Comment by dotsdl** [comment]
@davidlmobley is this submission still of interest to us? If not, we will close it for now and re-open if needed.

**Comment by davidlmobley** [comment]
Also still of interest, again, should be easier to do now that @jthorton 's work is coming along. Josh, can you have this on your radar too?

(basically once it won't take a good chunk of human time to get this ready, we should shove it through -- both optimizations and torsion drives.)

**Comment by j-wags** [comment]
* Dataset name: `Ehrman Informative Optimization v1.0` 
* priority --> low
* Submit after all genentech sets (#48)
* Do not expand states
* Max 40 conformers per molecule (though most molecules are almost entirely rigid so we should practically never get this many)

**Comment by jthorton** [comment]
I have created a basic optimization dataset, however, when processing the molecules many warnings were raised about missing stereochemistry, if we want to expand the states I can remake the dataset. For details on how it was made see the notebook used.

**Comment by j-wags** [comment]
I think it'd be ok to expand the stereo states.

**Comment by dotsdl** [comment]
This set of molecules has been submitted as `"OpenFF Ehrman Informative Optimization v0.2"`. `v0.1` had an issue in its JSON input `scf_properties` (`qudrupole` -> `quadrupole`), so v0.2 is currently being submitted with the fix in place.

**Comment by dotsdl** [comment]
`"OpenFF Ehrman Informative Optimization v0.2"` is now submitted!

**Comment by davidlmobley** [comment]
Thanks! And definitely OK to expand stereo. :)

**Pull request merged**
