### PR TITLE
Theory benchmarking datasets with B3LYP-D3BJ/def2-TZVPPD and B3LYP-D3BJ/6-31+G** 

### PR DESCRIPTION
**Pull request by hyejang**
- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset is named `dataset.json`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [ ] QCSubmit validation passed
- [ ] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
@hyejang is this still WIP? Or are you ready for a review? We can also directly operate on the PR to get it through validation.

**Review by trevorgokey — APPROVED** [review]
Looks good, I will go ahead and push this through.

Minor note: since the molecules themselves do not have CMILES info, this dataset is not eligible for any MM specs. Likely not an issue, so not a blocker.

**Comment by hyejang** [comment]
@dotsdl @trevorgokey  yea i think they are ready to go but it fails to pass the dataset validation. looks like my dataset is missing 'qc_specifications'. any suggestion on this?

**Comment by trevorgokey** [comment]
This submission is blocked by https://github.com/openforcefield/qcsubmit/issues/56

**Comment by dotsdl** [comment]
Hi @hyejang!

Thanks for putting this together. I'm on the road, but put together the following which should help:

Upgrade your QCSubmit installation with `conda update -c omnia/label/rc qcsubmit`.

In your notebook for e.g. `6-31+G**`, before you call `dataset.export_dataset("dataset.json")`, add a:

```
dataset.qc_specifications.pop('default')
dataset.add_qc_spec(method="B3LYP-D3BJ",
                    basis="6-31+G**",
                    program="psi4", 
                    spec_name="default",
                    spec_description="A torsiondrive dataset for benchmarking B3LYP-D3BJ/6-31+G**")
```

Do the same for `tzvppd`. 

This will set the "default" spec to have the appropriate method/basis/program for each dataset.
This is to maintain consistency with the previous datasets with the same torsions but different basis sets:
- dzvp
- tzvp
- tzvpd
- tzvpp

For future submissions with multiple method/basis/compute specs, we'll want to stack additional compute specs onto the same dataset if possible.

**Comment by dotsdl** [comment]
Please let us know if this inspires any additional questions. Our process has evolved since your previous submission of this type in July, so we want to help make this as painless as possible. Thanks for your patience!

**Comment by trevorgokey** [comment]
@hyejang I have updated the notebooks to use the current version of QCSubmit. They are good to go, and will be submitted today.

**Review by trevorgokey — APPROVED** [review]

**Comment by trevorgokey** [comment]
New snag; the basis set exchange only recognizes 6-31PGSS, so we will need to get around this in QCS so that it passes standard validation. Apologies for the delay!

**Comment by dotsdl** [comment]
@jthorton is there something special we will need to do to support a `def2-TZVPPD` compute spec?

**Comment by jthorton** [comment]
@trevorgokey @dotsdl This should now be ready to go using the newest version of QCSubmit.

**Comment by dotsdl** [comment]
Awesome, thanks @jthorton!

**Comment by pavankum** [comment]
@dotsdl or @JoshHorton  when you have a moment can you check on the issue with premature archiving of this dataset

**Comment by dotsdl** [comment]
Investigating this now; thanks @pavankum!

**Comment by dotsdl** [comment]
@pavankum both datasets in this submission have 36 complete Torsiondrives. Did you mean #173?

**Comment by pavankum** [comment]
Thank you very much @dotsdl , yeah it is #173 sorry I wrongly tagged this PR.

**Comment by pavankum** [comment]
the one we discussed in the last qca meeting about ds.status() and ds.status(status='COMPLETE') showing different results,
`ds = client.get_collection("TorsionDriveDataset", 'OpenFF Theory Benchmarking Set v1.0')`

**Pull request merged**
