### PR TITLE
Added rna-bgsu-dataset-v1.0

### PR DESCRIPTION
**Pull request by kntkb**
## New Submission Checklist

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Made a new dataset entry in the mapping table in repository `README.md`
- [x] Ready to submit!

## Compute Expansion Checklist

- [ ] Compute expansion filename matches pattern `compute*.json`; may feature a compression extension, such as `.bz2`
- [ ] QCSubmit validation passed
- [ ] Ready to submit!

### CODE REVIEW

**Comment by kntkb** [comment]
Hi @jchodera! I made a submission request for the RNA dataset. I was not sure who I should request the review so I tagged you to kindly inform you about the PR. 

If 7873 conformers are too many, I can potentially down size it to about 4500 conformers.

**Comment by pavankum** [comment]
Hi @kntkb, thank you very much for the submission. @dotsdl and I would review this soon and update you.

**Review by pavankum — CHANGES_REQUESTED** [review]
@kntkb I did a first pass of the PR and most of it looks good to me. Few minor points
- Are you planning to use any of the SCF properties: dipoles, quadrupoles, mayer/wiberg indices, mbis values, and wavefunction values in your work? If not, please modify the qc specification as follows and regenerate the dataset files
```
factory = BasicDatasetFactory(driver=DriverEnum.gradient, 
                              qc_specifications={ 'default': QCSpec(method='wb97m-d3bj', 
                                                                    basis='def2-tzvppd', 
                                                                    program='psi4', 
                                                                    spec_name='rna_default', 
                                                                    spec_description='RNA quantum chemistry specification', 
                                                                    store_wavefunction="none", 
                                                                    implicit_solvent=None, 
                                                                    maxiter=200, 
                                                                    scf_properties=[], 
                                                                    keywords={'wcombine': False}) },
                             store_wavefunction="none")
```
- dataset.visualize() is failing because of [a minor bug in qcsubmit call to rdkit](https://github.com/openforcefield/openff-qcsubmit/issues/200). Thanks for making your own visualize function, if possible can you increase the resolution and reduce number of mols per row to make the pictures a bit more clear (some of these are stacked molecules so it is of low priority of get these pictures correct, I can give it a try). Also, we just keep the visualizations of unique molecules.
cc: @dotsdl everything else looks good to me, I didn't understand the validation failure due to bad credentials, when you have a moment please take a look.
FYI @kntkb, @dotsdl is traveling for a conference this week so his review might be a bit delayed.

**Comment by pavankum** [comment]
@dotsdl the validation failure might be because of an external PR, it worked in #301

**Comment by pavankum** [comment]
@kntkb I can push the changes to qcspecification in the new PR if you give a go ahead on the scf properties you need

**Comment by j-wags** [comment]
Ugh, our CI OpenEye license seems to have just expired. That might be the external factor. I've emailed them for a new one and will let you know once it's updated.

**Comment by kntkb** [comment]
> @kntkb I did a first pass of the PR and most of it looks good to me. Few minor points
> 
> * Are you planning to use any of the SCF properties: dipoles, quadrupoles, mayer/wiberg indices, mbis values, and wavefunction values in your work? If not, please modify the qc specification as follows and regenerate the dataset files
> 
> ```
> factory = BasicDatasetFactory(driver=DriverEnum.gradient, 
>                               qc_specifications={ 'default': QCSpec(method='wb97m-d3bj', 
>                                                                     basis='def2-tzvppd', 
>                                                                     program='psi4', 
>                                                                     spec_name='rna_default', 
>                                                                     spec_description='RNA quantum chemistry specification', 
>                                                                     store_wavefunction="none", 
>                                                                     implicit_solvent=None, 
>                                                                     maxiter=200, 
>                                                                     scf_properties=[], 
>                                                                     keywords={'wcombine': False}) },
>                              store_wavefunction="none")
> ```
> 
> * dataset.visualize() is failing because of [a minor bug in qcsubmit call to rdkit](https://github.com/openforcefield/openff-qcsubmit/issues/200). Thanks for making your own visualize function, if possible can you increase the resolution and reduce number of mols per row to make the pictures a bit more clear (some of these are stacked molecules so it is of low priority of get these pictures correct, I can give it a try). Also, we just keep the visualizations of unique molecules.
>   cc: @dotsdl everything else looks good to me, I didn't understand the validation failure due to bad credentials, when you have a moment please take a look.
>   FYI @kntkb, @dotsdl is traveling for a conference this week so his review might be a bit delayed.



> @kntkb I did a first pass of the PR and most of it looks good to me. Few minor points
> 
> * Are you planning to use any of the SCF properties: dipoles, quadrupoles, mayer/wiberg indices, mbis values, and wavefunction values in your work? If not, please modify the qc specification as follows and regenerate the dataset files
> 
> ```
> factory = BasicDatasetFactory(driver=DriverEnum.gradient, 
>                               qc_specifications={ 'default': QCSpec(method='wb97m-d3bj', 
>                                                                     basis='def2-tzvppd', 
>                                                                     program='psi4', 
>                                                                     spec_name='rna_default', 
>                                                                     spec_description='RNA quantum chemistry specification', 
>                                                                     store_wavefunction="none", 
>                                                                     implicit_solvent=None, 
>                                                                     maxiter=200, 
>                                                                     scf_properties=[], 
>                                                                     keywords={'wcombine': False}) },
>                              store_wavefunction="none")
> ```
> 
> * dataset.visualize() is failing because of [a minor bug in qcsubmit call to rdkit](https://github.com/openforcefield/openff-qcsubmit/issues/200). Thanks for making your own visualize function, if possible can you increase the resolution and reduce number of mols per row to make the pictures a bit more clear (some of these are stacked molecules so it is of low priority of get these pictures correct, I can give it a try). Also, we just keep the visualizations of unique molecules.
>   cc: @dotsdl everything else looks good to me, I didn't understand the validation failure due to bad credentials, when you have a moment please take a look.
>   FYI @kntkb, @dotsdl is traveling for a conference this week so his review might be a bit delayed.

@pavankum Thanks for the review! Please let me get back to you about the SCF properties later. I will try to visualize the molecules with higher resolutions and keep only the unique molecules this time.

**Comment by pavankum** [comment]
@kntkb No need to worry about the visualization, I made some modifications on #301. Right now validation may fail for external PRs so I made a copy of yours there, I am happy to push any updates there if it is okay with you.

**Comment by pavankum** [comment]
@kntkb Sure, no problem. Go ahead and push the changes whenever you make them.

**Comment by kntkb** [comment]
Hi @pavankum! I removed the `mbis` and `wavefunction` options from the SCF properties. Also, the size of the dataset is decreased from 7873 to 4489 conformers. If possible, I would like to calculate with the OpenFF default level of theory as well. If this should be a separate submission, please let me know.

**Comment by pavankum** [comment]
Thank you for the updates @kntkb ! I will take a look later in the day, one more question regarding SCF properties, do you need the wiberg and mayer bond orders as well?

> If possible, I would like to calculate with the OpenFF default level of theory as well

Sure, I can add that compute spec as well to this submission.

**Comment by pavankum** [comment]
@kntkb Just reviewed the submission, it looks great! Thanks again for putting this together. Since validation is failing for non-repo user submissions I ported all the changes in this PR to #301. Barring any other changes #301 will be merged soon.

**Comment by kntkb** [comment]
@pavankum Thanks for the quick review!

>I will take a look later in the day, one more question regarding SCF properties, do you need the wiberg and mayer bond orders as well?

I do not plan to use wiberg and mayer bond orders for my work. I think these are default properties computed by the OpenFF's default setting. I thought it will be useful for future studies. However, the priority is very low. I can remove them if it is not commonly calculated by other communities or will cause storage concerns.

**Comment by pavankum** [comment]
> I do not plan to use wiberg and mayer bond orders for my work. I think these are default properties computed by the OpenFF's default setting. I thought it will be useful for future studies. However, the priority is very low. I can remove them if it is not commonly calculated by other communities or will cause storage concerns.
Thank you for the clarification @kntkb. I can make the changes and push it to compute then. Yeah, we used to compute all SCF properties anticipating future use but over time it started blowing up the storage on QCA, so we are a bit cautious these days and storing what we actually need.

**Comment by pavankum** [comment]
@kntkb The dataset is pushed to compute, you can follow the progress on the other PR #301, https://github.com/openforcefield/qca-dataset-submission/pull/301#issuecomment-1185125096.

**Comment by dotsdl** [comment]
Closing since this is superseded by #301.

**Pull request closed without merging**
