### PR TITLE
README clean up and index table.

### PR DESCRIPTION
**Pull request by jthorton**
This adds an INDEX.md to map the datasets in QCArchive to the submissions in this repo.

I have also cleaned up some old READMEs with incorrect dataset names and added compression to old datasets.

### CODE REVIEW

**Comment by dotsdl** [comment]
Thanks for putting this together @jthorton! Is this still WIP, or are you ready for review?

**Comment by jthorton** [comment]
@dotsdl I think this is ready please feel free to review, one thought I had is that it might be hard to maintain the status of the table as this is constantly changing, this could probably be automated or we could change the badge to be the quality of the dataset?

**Comment by dotsdl** [comment]
@jthorton is there an updater script that you used to generate the table? If we include that in `devtools` or `management`, we could wrap a Github Action around it in a future PR.

**Review by trevorgokey — APPROVED** [review]
This looks really good @jthorton! I didn't realize how much other clean up was done in this PR. I added a bit to some descriptions in the INDEX.md. This looks good to go!

**Pull request merged**
