### PR TITLE
Single points

### PR DESCRIPTION
**Pull request by pavankum**
#220 redone with lowercase keywords to get through https://github.com/openforcefield/qca-dataset-submission/pull/220#issuecomment-920810867
one extra change, added an extra spec b3lyp-nl
cc: @jthorton @dotsdl

### CODE REVIEW

**Review by jthorton — APPROVED** [review]
This looks great @pavankum thanks for the quick fix. I am not 100% sure what will happen with the automation here but lets give it a shot. 

One side note is that QCFractal actually splits up single point calculations when using D3 corrections into two tasks one at the underlying QM method and the other just using the correction this might cause some confusion to the error cycling and status reporting which we should look out for. This also can be confusing when pulling results as they must be combined.

**Comment by pavankum** [comment]
Thank you @jthorton for the review!

> One side note is that QCFractal actually splits up single point calculations when using D3 corrections into two tasks one at the underlying QM method and the other just using the correction this might cause some confusion to the error cycling and status reporting which we should look out for. This also can be confusing when pulling results as they must be combined.

Ohh, is this new now? I thought psi4 would internally call dftd3 post scf and add the correction.

**Comment by jthorton** [comment]
> Ohh, is this new now?

No I think QCFractal has always worked this way, I think this makes it easier to see the effect of the correction. 

> I thought psi4 would internally call dftd3 post scf and add the correction.

Normally that should happen but if you check this dataset in QCArchive and call `ds.data.history` you can see QCFractal actually splits the calculation up one for the method in psi4 and one for the correction in dftd3. So psi4 does not even know about the correction here. This has caught me out a few times when trying to pull down results.

**Comment by pavankum** [comment]
> > I thought psi4 would internally call dftd3 post scf and add the correction.
> 
> Normally that should happen but if you check this dataset in QCArchive and call `ds.data.history` you can see QCFractal actually splits the calculation up one for the method in psi4 and one for the correction in dftd3. So psi4 does not even know about the correction here. 

the stdout of the psi4 energy runs show empirical dispersion correction, this is a sample
```
  @DF-RKS Final Energy: -1067.07572793849931

   => Energetics <=

    Nuclear Repulsion Energy =           1182.2807469126205433
    One-Electron Energy =               -3824.0255865302706297
    Two-Electron Energy =                1671.1029762064911210
    DFT Exchange-Correlation Energy =     -96.3717714173404119
    Empirical Dispersion Energy =          -0.0620931100000000
    VV10 Nonlocal Energy =                  0.0000000000000000
    Total Energy =                      -1067.0757279384993126

Computation Completed
```
that made me think that psi4 already interacts with dftd3 and includes the dispersion correction. 

> This has caught me out a few times when trying to pull down results.

when accessing the scf_properties the final energy would be the corrected energy, right? anything in specific to be aware of?

**Comment by pavankum** [comment]
@jthorton I am looking at the QCA response here
`{'default': 4496, 'b3lyp-nl/dzvp': 2248, 'b3lyp-d3bj/def2-tzvp': 4496, 'b3lyp-d3bj/def2-tzvpd': 4496, 'b3lyp-d3bj/def2-tzvpp': 4496, 'b3lyp-d3bj/def2-tzvppd': 4496, 'b3lyp-d3bj/def2-qzvp': 4496, 'b3lyp-d3bj/6-31+g**': 4496, 'b3lyp-d3bj/6-311+g**': 4496, 'b97-d3bj/def2-tzvp': 4496, 'm05-2x-d3/dzvp': 4496, 'm06-2x-d3/dzvp': 4496, 'm08-hx-d3/dzvp': 4496, 'wb97x-d3bj/dzvp': 4496, 'wb97m-d3bj/dzvp': 4496, 'wb97m-v/dzvp': 2248, 'pw6b95-d3bj/dzvp': 4496, 'pw6b95-d3/dzvp': 4496, 'b3lyp-d3mbj/dzvp': 4496, 'mp2/aug-cc-pvtz': 2248, 'dsd-blyp-d3bj/heavy-aug-cc-pvtz': 4496, 'df-ccsd(t)/cbs': 2248}`

and it seems odd, I have 1416 geometries per qcspec, 24 each under 59 indices, and I can't connect to the numbers here. Any idea what's going on here or how to interpret ?

cc: @dotsdl

**Comment by pavankum** [comment]
|            |   default |   b3lyp-nl/dzvp |   b3lyp-d3bj/def2-tzvp |   b3lyp-d3bj/def2-tzvpd |   b3lyp-d3bj/def2-tzvpp |   b3lyp-d3bj/def2-tzvppd |   b3lyp-d3bj/def2-qzvp |   b3lyp-d3bj/6-31+g** |   b3lyp-d3bj/6-311+g** |   b97-d3bj/def2-tzvp |   m05-2x-d3/dzvp |   m06-2x-d3/dzvp |   m08-hx-d3/dzvp |   wb97x-d3bj/dzvp |   wb97m-d3bj/dzvp |   wb97m-v/dzvp |   pw6b95-d3bj/dzvp |   pw6b95-d3/dzvp |   b3lyp-d3mbj/dzvp |   mp2/aug-cc-pvtz |   dsd-blyp-d3bj/heavy-aug-cc-pvtz |   df-ccsd(t)/cbs |
|:-----------|----------:|----------------:|-----------------------:|------------------------:|------------------------:|-------------------------:|-----------------------:|----------------------:|-----------------------:|---------------------:|-----------------:|-----------------:|-----------------:|------------------:|------------------:|---------------:|-------------------:|-----------------:|-------------------:|------------------:|----------------------------------:|-----------------:|
| COMPLETE   |      1415 |            1413 |                   1410 |                    1415 |                    1411 |                     1414 |                   1414 |                  1407 |                   1414 |                    0 |             1415 |             1412 |             1416 |              1414 |                 0 |           1415 |               1414 |             1414 |               1415 |              1416 |                              1412 |             1215 |
| ERROR      |         0 |               0 |                      0 |                       0 |                       0 |                        0 |                      0 |                     0 |                      0 |                 1416 |                0 |                0 |                0 |                 0 |              1416 |              0 |                  0 |                0 |                  0 |                 0 |                                 0 |                0 |
| INCOMPLETE |         1 |               3 |                      6 |                       1 |                       5 |                        2 |                      2 |                     9 |                      2 |                    0 |                1 |                4 |                0 |                 2 |                 0 |              1 |                  2 |                2 |                  1 |                 0 |                                 4 |              201 |


date and time = 21/10/2021 17:53:00

**Comment by dotsdl** [comment]
Re-added tracking with public QCA now at v0.15.7; should avoid query timeouts.

**Comment by dotsdl** [comment]
Remaining errors are systematic. Moving to Archived/Complete @pavankum.

**Comment by pavankum** [comment]
@dotsdl it seems odd that none of the `wb97m-d3bj/dzvp` runs went through, but `b97-d3bj` had successes, for now can you please move this to scientific review instead of archiving, I will check and get back to you :)

**Comment by pavankum** [comment]
@dotsdl Apologies, I checked again and they're indeed complete, I saw the table above and mistook that they're incomplete, I think we're good, sorry for the confusion :)

**Pull request merged**
