### PR TITLE
SPICE DES370K (multi-molecule)

### PR DESCRIPTION
**Pull request by pavankum**
## New Submission Checklist

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Made a new dataset entry in the mapping table in repository `README.md`
- [x] Ready to submit!

### CODE REVIEW

**Comment by pavankum** [comment]
@jthorton / @dotsdl another error to look into when you have time, 
```
ValidationError: 1 validation error for Molecule
connectivity
  ensure this value has at least 1 items (type=value_error.list.min_items; limit_value=1)
```

**Comment by jthorton** [comment]
@pavankum this should be fixed in the newest toolkit release see the patch here https://github.com/openforcefield/openff-toolkit/pull/1101.

**Comment by pavankum** [comment]
Thank you @jthorton :)

**Comment by dotsdl** [comment]
@pavankum I see both `des370k.hdf5.tar.gz` and `des370k.tar.gz` in the directory. Is this intentional? It looks like they feature the same contents?

**Comment by pavankum** [comment]
> @pavankum I see both `des370k.hdf5.tar.gz` and `des370k.tar.gz` in the directory. Is this intentional? It looks like they feature the same contents?

I might've included by mistake, will delete one

**Review by jthorton — CHANGES_REQUESTED** [review]
Thanks for putting this together @pavankum. I think we need to confirm that the fragments in  the qcelemental molecules are in a continuous ordering before we submit or we will run into the error we see [here](https://github.com/openforcefield/qca-dataset-submission/pull/239#issuecomment-970322729)

**Comment by pavankum** [comment]
> Thanks for putting this together @pavankum. I think we need to confirm that the fragments in the qcelemental molecules are in a continuous ordering before we submit or we will run into the error we see [here](https://github.com/openforcefield/qca-dataset-submission/pull/239#issuecomment-970322729)

@jthorton do you think those errors would be specific for the multi-molecule systems?

**Comment by dotsdl** [comment]
@pavankum is this one ready to go too?

**Comment by pavankum** [comment]
@dotsdl this is good to go, to be sure that there are no further issues may be we can push the smaller set of solvated amino acids  first #257 ?

**Comment by dotsdl** [comment]
@pavankum I can review this one today too now that #257 is through; what do you think?

**Comment by pavankum** [comment]
@dotsdl Sure, that'd be great!

**Comment by dotsdl** [comment]
@peastman to confirm, you don't need wavefunctions on this dataset? I'd like to avoid it if possible, or hold off on submission if you are uncertain.

**Comment by peastman** [comment]
Correct.  I don't need wavefunctions on any of the datasets.

**Review by dotsdl — APPROVED** [review]
This is ready to go; will likely need to be launched manually due to number of conformers (345k). I have set `store_wavefunction: "none"` for this set.

**Comment by dotsdl** [comment]
@jthorton are you satisfied given [your comment earlier](https://github.com/openforcefield/qca-dataset-submission/pull/244#pullrequestreview-807470931)?

**Comment by jthorton** [comment]
@dotsdl as long as this was regenerated with the fixed version of qcsubmit it should be fine.

**Comment by dotsdl** [comment]
@pavankum and @bennybp, are either of you opposed to me submitting this? Or would this be playing with fire at this time?

**Comment by pavankum** [comment]
@dotsdl I have no objections, feel free to merge if Ben agrees.

**Comment by pavankum** [comment]
just for reference number of heavy atoms is less than 15 or so in each, so this shouldn't take up much space

**Comment by dotsdl** [comment]
Cool, thanks! Merging and submitting! Also got an affirmative from @bennybp that we should be okay here.

**Comment by dotsdl** [comment]
This submission is currently being submitted locally through `vulkan` due to its size.

**Comment by pavankum** [comment]
since the error_cycling is choking a bit because of the larger dataset size I checked locally and the completion rate is impressive

|            |   spice |
|:-----------|--------:|
| COMPLETE   |  234068 |
| ERROR      |   43284 |
| INCOMPLETE |   68330 |
| NaN        |       0 |

**Comment by peastman** [comment]
Thanks!  These are really small dimers.  The median size is 16 atoms, including hydrogens.  They go fast.

**Comment by peastman** [comment]
I think PacificResearchPlatformQM is preventing us from completing this.  We could easily get through the remaining calculations in a single day.  But it grabs almost all of them and produces errors, which prevents any other cluster from doing them.

**Comment by pavankum** [comment]
Yeah, it's a sticky situation, we opted for slow progress instead of zero progress on PRP until the new backend changes are adapted in the production environments. We can stop sending spice jobs to PRP by re-tagging this set and setting up managers specifically for that tag, @dotsdl any thoughts?

**Comment by dotsdl** [comment]
I can also just shut off our PRP workers devoted to SPICE. I'll do that if that's preferable at this point.

**Comment by dotsdl** [comment]
Deleted SPICE deployment on PRP.

**Comment by peastman** [comment]
Thanks!  We can turn them back on once the fix is deployed.

**Comment by pavankum** [comment]
All the errors are from MBIS charge calculation, except one with SCF convergence, if 99% completion rate is acceptable we can move this dataset to end of life so that we can avoid rerunning the consistent failures.

**Comment by peastman** [comment]
It's probably acceptable.  Can we retrieve a list of which samples had the errors?

**Comment by pavankum** [comment]
Here is a notebook to extract the failed inputs, I picked the smiles of first 100 errors as a sample

[jupyter_notebook.tar.gz](https://github.com/openforcefield/qca-dataset-submission/files/8052486/jupyter_notebook.tar.gz)

**Comment by pavankum** [comment]
If the errors are only with MBIS charges we can build a supplementary dataset with those particular records, removing MBIS calculation.

**Comment by peastman** [comment]
That would be great.  The charges are only there because we thought they might be useful to someone.  We're mostly interested in forces and energies though.

**Comment by peastman** [comment]
It's interesting that all of the first 100 involve a Na+ or Li+ ion interacting with some larger, neutral molecule.  I don't know if there's a particular reason those tend to be more difficult to solve.

**Pull request merged**
