### PR TITLE
[PEPCONF] Add WB97X/6-31G* QC spec

### PR DESCRIPTION
**Pull request by dotsdl**
- [ ] Created a new folder in the submissions directory containing the dataset
- [x] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [ ] Dataset is named `dataset.json`
- [ ] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
@jchodera, if you're satisfied with the [QC spec](https://github.com/openforcefield/qca-dataset-submission/pull/172/files#diff-c2248e4a8ba57bc8e3b7d7c5073fd4faa3ff6e6fff5411d46e667cbe0f8d58ab), we can proceed to merge. This will submit this spec and add it for compute on the PEPCONF submission.

**Review by jchodera — APPROVED** [review]
Looks great to me!

**Comment by dotsdl** [comment]
@jchodera this compute spec is showing a large number of SCF convergence errors on this dataset, and we have yet to successfully complete an Optimization from it. One thing we could try before anything else:
1. I can can re-tag the dataset with a compute tag specific to this exploratory project, e.g. `openff-pepconf`.
2. You can add this compute tag to your manager config as:

```
manager:
    queue_tag: 
        - openff-pepconf
        - openff
```
3. Hardcode the SCF convergence limit on your manager to a higher value, such as 1000.
4. Start up manager.

Is this an approach you'd like to take?

**Comment by jchodera** [comment]
@dotsdl : Thanks for giving this a go! I actually tried increasing the SCF maxiters to 20000 yesterday. Let's give it one more day, and then scrap it if that fails too.

**Comment by jchodera** [comment]
We'll obviously need some professional QC help here.

**Comment by dotsdl** [comment]
@jchodera no problem; I turned off error cycling yesterday until we knew your preference for next steps. I'll error cycle it one more time so we have visibility here on how it is behaving, then I'll move this to "Requires Scientific Review".

**Comment by jchodera** [comment]
@dotsdl : Thanks for giving this a try!

**Pull request merged**
