### PR TITLE
SPICE Dipeptides Optimization Set

### PR DESCRIPTION
**Pull request by pavankum**
## New Submission Checklist

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Made a new dataset entry in the mapping table in repository `README.md`
- [x] Ready to submit!

### CODE REVIEW

**Review by dotsdl — APPROVED** [review]
Looks great @pavankum!

Some questions before we go further:

1. Do we want just a single conformer/optimization per molecule? Depending on the downstream needs we may benefit from having several conformers, as these may each find their own, different local minima.
2. Do you expect to need the wavefunction from any of these? We currently don't get wavefunctions attached to *any* of the `ResultRecord`s that make up the optimization sequence. I have in my queue to draft a solution to this in QCFractal, but it isn't in place yet.

**Comment by pavankum** [comment]
> Some questions before we go further: Do we want just a single conformer/optimization per molecule? Depending on the downstream needs we may benefit from having several conformers, as these may each find their own, different local minima.
@dotsdl that's a great catch, thanks for pointing that! Yeah, that makes sense, will modify the submission with max_confs of 50. 

>  Do you expect to need the wavefunction from any of these? We currently don't get wavefunctions attached to any of the ResultRecords that make up the optimization sequence. I have in my queue to draft a solution to this in QCFractal, but it isn't in place yet.
hmmm, I guess we can get away with energies/forces for this one, John wanted an optimization set to compare which conf. generation scheme is doing well.

**Comment by pavankum** [comment]
@dotsdl Thanks for your review, I updated the submission, let me know if this looks good now, and if I can go ahead with the squash merge.

**Comment by jthorton** [comment]
Looks great @pavankum just 2 points:
1. can we remove the `orbitals_and_eigenvalues` as they won't be saved anyway and it helps keep it clear what is to be expected in the dataset.
2. The other peptide dataset has around 50 diverse conformers per molecule, maybe we should try and generate a lot more conformers here to make the two comparable?

**Comment by pavankum** [comment]
> Looks great @pavankum just 2 points:
> 
>     1. can we remove the `orbitals_and_eigenvalues` as they won't be saved anyway and it helps keep it clear what is to be expected in the dataset.
Thank you for the review @jthorton , sure will update.
> 
>     2. The other peptide dataset has around 50 diverse conformers per molecule, maybe we should try and generate a lot more conformers here to make the two comparable?
Initially I thought of adding 50 conformers but since this is an opt set with def2-tzvppd I backed out fearing this may take forever to complete with the larger basis,. For a fair comparison it makes sense to have same number of confs, will update.

**Comment by jchodera** [comment]
@pavankum Should this dataset have been terminated now that the [SPICE Dipeptides revised v1.1 dataset](https://github.com/openforcefield/qca-dataset-submission/pull/259) is active (but making no progress)?

**Comment by pavankum** [comment]
@jchodera this is the full optimization dataset and the other one is just single points. This was submitted for the purpose of comparing conformer selection strategies, MD based conformers versus regular toolkit generated conformers.

**Comment by pavankum** [comment]
@dotsdl we can lower the priority on this one and after all single point datasets are evaluated we can push this

**Comment by jchodera** [comment]
> @jchodera this is the full optimization dataset and the other one is just single points. This was submitted for the purpose of comparing conformer selection strategies, MD based conformers versus regular toolkit generated conformers.

Ah, thanks! I didn't catch that!

> @dotsdl we can lower the priority on this one and after all single point datasets are evaluated we can push this

That sounds reasonable!

**Pull request merged**
