### PR TITLE
Add version2 of the protein dataset.

### PR DESCRIPTION
**Pull request by jthorton**
- [X] Created a new folder in the submissions directory containing the dataset
- [X] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [X] All files used to produce the dataset are included with a description
- [X] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [X] Dataset is named `dataset.json`
- [X] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [ ] QCSubmit validation passed
- [ ] Ready to submit!

### CODE REVIEW

**Comment by jthorton** [comment]
@dscerutti @dotsdl @j-wags Hey guys here is the full protein dataset which should also fix the incorrect CMILES strings due to the mol2 connectivity issue. I have also found some molecules to have net non-zero charges and just want to make sure that is correct and expected. @dscerutti I found a total of 185 unique molecules and 6716 total conformations.

**Comment by j-wags** [comment]
Took a quick look at the SMILES and PDF -- No objections here, but @dscerutti should be the final approver.

I see that some of the molecules in the PDF are drawn with colors and others have element symbols. Long-term it would be good to standardize on element symbols. 

Also, is it possible to back-port the correct CMILES onto the v1 dataset? Or would we want to make a v1.1 that fixes the labels? Or just clearly state somewhere that the v1 dataset is fully superseded by the v2?

**Comment by dotsdl** [comment]
Moved to "Requires Scientific Review" as this submission is no longer advancing. @jthorton are we fine with the one missing `OptimizationRecord`, or do we want to make adjustments to get it to converge?

**Comment by dotsdl** [comment]
Declaring End-of-Life for this submission. Submission #141 supersedes this one.

**Pull request merged**
