### PR TITLE
Updating prod envs for compute deployments

### PR DESCRIPTION
**Pull request by dotsdl**
Attempting to use latest packages, pinning where appropriate to create some degree of determinism over time for the most important packages when building prod instances from these environments.

### CODE REVIEW

**Comment by dotsdl** [comment]
@bennybp can I get a spot-check on these envs for suitability as compute manager environments? We'll also use these for supporting our Docker-based manager deployments.

**Comment by bennybp** [comment]
I think those are reasonable, at least at first glance. The only thing might be that you don't need explicit `gau2grid` anymore with the conda-forge psi4 packages.

**Comment by dotsdl** [comment]
Awesome, thank you @bennybp!

**Comment by dotsdl** [comment]
Got the envs building successfully now: https://github.com/openforcefield/qca-dataset-submission/actions/runs/6938585368

`pytorch` isn't happy with python 3.10 or 3.11, and the mamba solver errors are baffling. Choosing 3.11 and we get complaints that 3.10 is possible, but choosing 3.10 gives complaints that 3.11 is possible. Since it's unclear if there's any demand for `torchani` in the near or distant future, I've disabled build of this env in both prod env deployment and Docker build.

**Comment by dotsdl** [comment]
Will revisit `torchani` env if desired in the future.

**Pull request merged**
