### PR TITLE
OpenFF Protein Peptide Fragments unconstrained v1.0

### PR DESCRIPTION
**Pull request by dotsdl**
This submission features an `OptimizationDataset` using the same source molecules/conformers as #141, except *without* any constraints.

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added README.md describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset is named `dataset.json`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
Ready for review @trevorgokey! Renamed dataset to "OpenFF Protein Peptide Fragments unconstrained v1.0".

**Review by trevorgokey — APPROVED** [review]
Looks good!

**Comment by dotsdl** [comment]
Awesome, thank you @trevorgokey! Merging!

**Comment by dotsdl** [comment]
This submission is consistently throwing a lot of what look like memory errors. To reduce waste on our compute resources, I'm dropping the "tracking" label on it for now; this will exempt it from error cycling until we re-add the label.

**Pull request merged**
