### PR TITLE
OpenFF-multiplicity-correction-torsion-drive-data-v1.1

### PR DESCRIPTION
**Pull request by pavankum**
## Modified Submission Checklist -->  v1.1

- [ ] Updated `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [ ] All files used to produce the dataset are included with a description
- [ ] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [ ] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [ ] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [ ] QCSubmit validation passed
- [ ] Modified dataset entry in the mapping table in repository `README.md`
- [ ] Ready to submit!

### CODE REVIEW

**Comment by pavankum** [comment]
@jmaat Here is the updated submission, please review it when you have a moment, I added some additional molecules on top of your suggestions to have some substitutes for in-ring torsions in some parameters.

**Comment by jmaat** [comment]
Okay this looks great, thank you so much

**Review by jmaat — APPROVED** [review]
Looks good to go!

**Comment by dotsdl** [comment]
I removed the `compute-openff` label, since we also had the `compute-openff-uci` label. The automation will only apply one `compute-*` label with the `*` as a compute tag, so this should now route to the `openff-uci` compute tag for which we have many managers running.

**Comment by pavankum** [comment]
@jmaat Remaining are expected errors carried over from v1.0, moving this to end-of-life.

**Pull request merged**
