### PR TITLE
Protein Capped 3-mer Omega TorsionDrive

### PR DESCRIPTION
**Pull request by chapincavender**
This dataset scans the omega dihedral (CA-C-N-CA) in the central residue of capped 3-mers Ace-Ala-X-Ala-Nme.

## New Submission Checklist

- [x] Created a new folder in the submissions directory containing the dataset
- [x] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [x] All files used to produce the dataset are included with a description
- [x] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [x] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [x] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [x] QCSubmit validation passed
- [x] Made a new dataset entry in the mapping table in repository `README.md`
- [x] Ready to submit!

### CODE REVIEW

**Review by pavankum — APPROVED** [review]
Thanks for putting this together. LGTM @chapincavender!

**Comment by chapincavender** [comment]
Thanks for pushing the fix for the validation, @pavankum!

**Comment by pavankum** [comment]
@chapincavender Can you please merge master into this before merging this, I just updated the workflow yamls for all actions.

**Comment by pavankum** [comment]
@chapincavender @dotsdl When you have a moment can you please check the status of your workers.

**Comment by dotsdl** [comment]
Yes, apologies, haven't had a chance to investigate this yet.

**Comment by dotsdl** [comment]
Working to address stalled calculations now.

**Comment by dotsdl** [comment]
We were missing miniforge-variant: Mambaforge in the Action that performs retags/reprioritization. That Action has been failing without that addition, and so the new submission wasn't getting retagged to openff-tscc. I've fixed this and the Action works again.

To avoid #325 competing with old tasks, I've compute tagged it to openff-tscc-2. My local worker just picked one of these up.

Launching compute on cluster resources targeting this compute tag. We should see completes rolling in on next error cycle if those jobs pick up.

**Pull request merged**
