### PR TITLE
SPICE pubchem_set1 revised v1.1 (wcombine = False)

### PR DESCRIPTION
**Pull request by pavankum**
## New Submission Checklist

- [ ] Created a new folder in the submissions directory containing the dataset
- [ ] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [ ] All files used to produce the dataset are included with a description
- [ ] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [ ] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [ ] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [ ] QCSubmit validation passed
- [ ] Made a new dataset entry in the mapping table in repository `README.md`
- [ ] Ready to submit!

### CODE REVIEW

**Comment by dotsdl** [comment]
Did the following to effectively rebase against `master`:

```
git checkout master
git pull origin master
git checkout -b pubchem_set1-r
git cherry-pick pubchem_set1
git push --force origin pubchem_set1-r:pubchem_set1
```

@pavankum I recommend you delete your local `pubchem_set1` branch and pull the new one, since your local branch will share no history with this one:

```
git branch -D pubchem_set1
git pull origin pubchem_set1
```

**Comment by dotsdl** [comment]
I will do the same to the other sets with the same issue.

**Comment by pavankum** [comment]
Thank you @dotsdl !! I did the following to resolve conflicts for #259  is that okay or should I revert the changes?
```
git pull
git checkout dipeptides
git merge -X ours master
```

**Comment by dotsdl** [comment]
@pavankum hmm, I haven't used that one before. From the description I think it should give a similar result in the end, favoring the new notebook and `dataset.json.bz2` binary.

**Comment by pavankum** [comment]
@dotsdl sounds good

**Comment by dotsdl** [comment]
@pavankum would you mind applying the same treatment to the other PRs? I think you have the less invasive solution here. :+1:

**Comment by pavankum** [comment]
@dotsdl I am confused that there is a validation report from `openff-dangerbot` with all [green ticks above](https://github.com/openforcefield/qca-dataset-submission/pull/260#issuecomment-989058998) but one check fails at the bottom :confused:

**Comment by dotsdl** [comment]
I just ran it locally to test out my fix. Will follow-up here when I've got it sorted fully. Sorry for the confusion!

**Comment by dotsdl** [comment]
@pavankum my method from above looks like it affected history on my `master` branch too. I think it was my `git pull origin pubchem_set1`, which should have been a `git fetch`. So when I pushed changes to fix validation to `master` it included the commits in this PR.

I think we're still good to go; this should get launched without any other issues.

**Comment by pavankum** [comment]
Great! Thank you so much for the fixes!!! :grin:

**Comment by pavankum** [comment]
@dotsdl do you think there would be a clash between the old set and new set, the compute spec name remains the same but additional keyword was introduced. The size of the set seems to show two times the dataset size, (2 x 118606) = 237,212

**Comment by dotsdl** [comment]
@pavankum and I met today to address these questions. We took a look at the dataset and its records and concluded that what is present on QCArchive is as expected. It is not clear, however, why the response gives a number 2x the number of records.

**Pull request merged**
